{
  "hash": "97f78eb625dfff8152f75fe64dcfbe62",
  "result": {
    "engine": "knitr",
    "markdown": "---\nformat: \n    live-html:\n        theme: cosmo\n        highlight-style: atom-one\n        css:\n         - include/quarto.css\n         - include/glossary.css\n         - include/webex.css\n        number-sections: true\n        toc-depth: 5\n        toc-expand: 4\n        toc_float: true\n        code-fold: true\n        code-summary: \"Show/hide the code\"\n        code-tools: true\n        code-link: true\n        code-overflow: scroll\n        df-print: default\n        link-external-newwindow: true\n        link-external-icon: true\n        include-after-body: include/webex.js\nwebr:\n    packages:\n        - cli\n        - generics\n        - glue\n        - magrittr\n        - utf8\n        - vctrs\n        - pillar\n        - R6\n        - fansi\n        - pkgconfig\n        - tibble\n        - withr\n        - tidyselect\n        - dplyr\n        \nengine: knitr\n---\n\n\n::: {.cell}\n\n:::\n\n\n\n\n# Approximating the Posterior {#sec-chap-006}\n\n\n\n\n\n::::: {#obj-chap-006}\n:::: {.my-objectives}\n::: {.my-objectives-header}\nObjectives\n:::\n\n::: {.my-objectives-container}\n\n- Implement and examine the limitations of using grid approximation to simulate a posterior model. \n- Explore the fundamental properties of <a class='glossary' title='Markov chain Monte Carlo (MCMC) methods comprise a class of algorithms for sampling from a probability distribution. By constructing a [markov chain] that has the desired distribution as its equilibrium distribution, one can obtain a sample of the desired distribution by recording states from the chain. The more steps that are included, the more closely the distribution of the sample matches the actual desired distribution. Various algorithms exist for constructing chains. (Wikipedia)'>MCMC</a> posterior simulation techniques and how these differ from grid approximation. \n- Implement MCMC simulation in R. \n- Learn several <a class='glossary' title='Markov chain is a stochastic model describing a sequence of possible events in which the probability of each event depends only on the state attained in the previous event.  This defining property is known as the Markov property or memorylessness, meaning the future state depends solely on the current state and not on the sequence of events that preceded it. (Brave-AI)'>Markov chain</a> diagnostics for examining the quality of an MCMC posterior simulation.\n\n\n:::\n::::\n:::::\n\n## Grid approximation\n\nWe needn’t observe $f (\\theta \\mid y)$ at every possible $\\theta$ to get a sense of its structure. Rather, we can evaluate $f (\\theta \\mid y)$ at a finite, discrete grid of possible $\\theta$ values. Subsequently, we can take random samples from this discretized pdf to approximate the full posterior pdf $f (\\theta \\mid y)$.\n\n:::::{.my-experiment}\n:::{.my-experiment-header}\n:::::: {#def-006-grid-approximation}\n: Grid approximation\n::::::\n:::\n::::{.my-experiment-container}\nGrid approximation produces a sample of $N$ **independent** $\\theta$ values, $\\{\\theta(1), \\theta(2), . . . , \\theta(N)\\}$, from a **discretized approximation** of posterior pdf $f (\\theta \\mid y)$.\n::::\n:::::\n\n:::::{.my-procedure}\n:::{.my-procedure-header}\n:::::: {#prp-006-grid-approximation}\n: Grid approximation\n::::::\n:::\n::::{.my-procedure-container}\nThe grid approximation algorithm evolves in four steps:\n\n1. Define a discrete grid of possible $\\theta$ values. \n2. Evaluate the prior pdf $f (\\theta)$ and likelihood function $L(\\theta \\mid y)$ at each $\\theta$ grid value. \n3. Obtain a discrete approximation of the posterior pdf $f (\\theta \\mid y)$ by: \n    (a) calculating the product $f (\\theta)L(\\theta \\mid y)$ at each $\\theta$ grid value; and then \n    (b) normalizing the products so that they sum to $1$ across all $\\theta$. \n4. Randomly sample $N$ $\\theta$ grid values with respect to their corresponding normalized posterior probabilities.\n\n\n::::\n:::::\n\n### Beta-Binomial example\n\n#### Definition\n\nTo bring the grid approximation technique to life, let’s explore the following generic <a class='glossary' title='The Beta-Binomial Bayesian Model is a fundamental framework in Bayesian statistics used to estimate a proportion π (e.g., success probability) when data are binary outcomes (success/failure) across n independent trials. The Beta-Binomial Bayesian Model combines a Beta prior with a Binomial likelihood, resulting in a Beta posterior due to conjugacy.  This makes it ideal for estimating unknown proportions (e.g., success rates) from binary data.'>Beta-Binomial model</a> (one without a corresponding data story):  \n \n$$\n\\begin{align*}\nY \\mid \\pi &\\sim \\text{Bin}(10, \\pi) \\\\\n\\pi &\\sim \\text{Beta}(2, 2)\n\\end{align*}\n$$ {#eq-006-beta-binomial-example}\n\n  \nWe can interpret $Y$ here as the number of successes in $10$ independent trials. Each trial has probability of success $\\pi$ where our prior understanding about $\\pi$ is captured by a $\\text{Beta}(2, 2)$ model. Suppose we observe $Y = 9$ successes. Then by our work in @sec-chap-003, we know that the updated posterior model of $\\pi$ is Beta with parameters $11 \\quad (Y + \\alpha = 9 + 2)$ and $3 \\quad (n − Y +\\beta = 10 − 9 + 2)$:  \n\n$$\\pi \\mid (Y = 9) \\sim \\text{Beta}(11, 3)$$\n\n#### Approximation {#sec-006-approximation}\n\nWe’re now going to ask you to *forget* that we were able to specify this posterior. Instead, we’ll try to *approximate* the posterior using grid approximation.\n\n:::::{.my-procedure}\n:::{.my-procedure-header}\n:::::: {#prp-006-detailed-steps-of-grid-approximation}\n: Detailed steps of grid approximation\n::::::\n:::\n::::{.my-procedure-container}\n\n::: {#big-text style=\"font-size: 110%\"}\n**Step 1** \n:::\n\nwe need to split the continuum of possible $\\pi$ values on $0 to 1$ into a finite grid. We’ll start with a course grid of only $6$ $\\pi$ values, $\\pi \\in \\{0, 0.2, 0.4, 0.6, 0.8, 1\\}$:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# Step 1: Define a grid of 6 pi values \ngrid_data <- tibble::tibble(pi_grid = base::seq(from = 0, to = 1, length = 6))\n```\n:::\n\n\n::: {#big-text style=\"font-size: 110%\"}\n**Step 2** \n:::\n\nWe use `stats::dbeta()` and `stats::dbinom()`, respectively, to evaluate the $\\text{Beta}(2, 2)$ <a class='glossary' title='A prior represents the initial belief or knowledge about an uncertain quantity, such as a model parameter, before observing any data. It is formally defined as a probability distribution that quantifies the degree of belief in the parameter’s possible values based on previous information, expert opinion, or theoretical considerations.'>prior</a> <a class='glossary' title='A probability density function (PDF) describes a probability distribution for a random, continuous variable. Use a probability density function to find the chances that the value of a random variable will occur within a range of values that you specify. More specifically, a PDF is a function where its integral for an interval provides the probability of a value occurring in that interval. (Statistics By Jim)'>pdf</a> and $\\text{Bin}(10, \\pi)$ <a class='glossary' title='The likelihood function measures the plausibility of different parameter values given the observed data, rather than the probability of the data itself. It is not a probability distribution over the parameters, as it does not integrate or sum to one, and it is not normalized. Instead, it quantifies how likely the observed data are under different parameter settings. (Brave-AI)'>likelihood function</a> with $Y = 9$ at each $\\pi$ in `pi_grid`:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# Step 2: Evaluate the prior & likelihood at each pi\ngrid_data <- grid_data |>  \n  dplyr::mutate(prior = stats::dbeta(pi_grid, 2, 2),\n         likelihood = stats::dbinom(9, 10, pi_grid))\n```\n:::\n\n\n\n::: {#big-text style=\"font-size: 110%\"}\n**Step 3** \n:::\n\nWe calculate the product of the likelihood and prior at each grid value. This provides an *unnormalized* discrete approximation of the <a class='glossary' title='The posterior distribution represents the updated beliefs about the parameters of a model after incorporating observed data. It is derived by combining the prior distribution, which reflects initial beliefs about the parameter, with the likelihood of the observed data using Bayes’ theorem.'>posterior</a> pdf that doesn’t sum to one. We subsequently <a class='glossary' title='In Bayesian statistics, the normalizing constant ensures that the posterior distribution integrates to 1, making it a valid probability distribution. It is also known as the marginal likelihood or evidence, and appears in the denominator of Bayes’ theorem. The integral for the normalizing constant is often intractable for complex models because it involves high-dimensional parameter spaces and there exists no closed-form solution for most realistic models. As a result, approximation methods like Markov Chain Monte Carlo (MCMC), bridge sampling, or variational inference are used to estimate or bypass the normalizing constant. (Brave-AI)'>normalize</a> this approximation by dividing each unnormalized posterior value by their collective sum:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# Step 3: Approximate the posterior\ngrid_data <- grid_data |>  \n  dplyr::mutate(unnormalized = likelihood * prior,\n         posterior = unnormalized / sum(unnormalized))\n\n# Confirm that the posterior approximation sums to 1\ngrid_data |> \n  dplyr::summarize(sum(unnormalized), sum(posterior)) |> \n    knitr::kable(digits = 4)\n```\n\n::: {.cell-output-display}\n\n\n| sum(unnormalized)| sum(posterior)|\n|-----------------:|--------------:|\n|             0.318|              1|\n\n\n:::\n:::\n\n\n\nThe resulting discretized posterior pdf, rounded to 2 decimal places and plotted below, provides a very rigid glimpse into the *actual* posterior pdf. It places a roughly 99% chance on $\\pi$ being either $0.6$ or $0.8$, a 1% chance on $\\pi$ being 0.4, and a near 0% chance on the other $\\pi$ grid values:\n\n\n\n::: {#tbl-006-grid-approx-posterior .cell tbl-cap='Examine the grid approximated posterior'}\n\n```{.r .cell-code  code-fold=\"false\"}\n# Examine the grid approximated posterior\ngrid_data |> \n    knitr::kable(digits = 2)\n```\n\n::: {.cell-output-display}\n\n\n| pi_grid| prior| likelihood| unnormalized| posterior|\n|-------:|-----:|----------:|------------:|---------:|\n|     0.0|  0.00|       0.00|         0.00|      0.00|\n|     0.2|  0.96|       0.00|         0.00|      0.00|\n|     0.4|  1.44|       0.00|         0.00|      0.01|\n|     0.6|  1.44|       0.04|         0.06|      0.18|\n|     0.8|  0.96|       0.27|         0.26|      0.81|\n|     1.0|  0.00|       0.00|         0.00|      0.00|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# Plot the grid approximated posterior\nggplot2::ggplot(grid_data, \n                ggplot2::aes(x = pi_grid, y = posterior)) + \n  ggplot2::geom_point() + \n  ggplot2::geom_segment(\n      ggplot2::aes(x = pi_grid, xend = pi_grid, y = 0, yend = posterior))\n```\n\n::: {.cell-output-display}\n![Plot of the grid approximated posterior](006-approximating-posterior_files/figure-html/fig-006-grid-approx-posterior-1.png){#fig-006-grid-approx-posterior width=384}\n:::\n:::\n\n\n::: {#big-text style=\"font-size: 110%\"}\n**Step 4** \n:::\n\nEach sample draw has only 6 possible outcomes and is highly likely to be $0.6$ or $0.8$. Let’s try it: use `dplyr::slice_sample()` to take a sample of `n = 10000` values from the 6-length grid_data, with replacement, and using the discretized `posterior` probabilities as sample weights.\n\n\n::: {#tbl-sample-discretized-posterior .cell tbl-cap='Sample form the discetized Posterior'}\n\n```{.r .cell-code  code-fold=\"false\"}\n# Step 4: sample from the discretized posterior\n\n# Set the seed\nset.seed(84735)\n\npost_sample <- dplyr::slice_sample(grid_data, n = 10000, \n                        weight_by = posterior, replace = TRUE)\n\n\n# A table of the 10000 sample values\npost_sample |> \n  janitor::tabyl(pi_grid) |> \n  janitor::adorn_totals(\"row\") |> \n  knitr::kable(digits = 4)\n```\n\n::: {.cell-output-display}\n\n\n|pi_grid |     n| percent|\n|:-------|-----:|-------:|\n|0.4     |    69|  0.0069|\n|0.6     |  1885|  0.1885|\n|0.8     |  8046|  0.8046|\n|Total   | 10000|  1.0000|\n\n\n:::\n:::\n\n\nAs expected, most of our $10,000$ sample values of $\\pi$ were $0.6$ or $0.8$, few were $0.4$, and none were below $0.4$ or above $0.8$.\n\n\n\n\n\n::::\n:::::\n\nThis is an extremely oversimplified approximation of the true $\\text{Beta}(11, 3)$ posterior. If you need any more convincing, Figure 6.2 superimposes the true posterior pdf $f (\\pi \\mid y)$ on a scaled histogram of the $10,000$ sample values. If this were a good approximation, the histogram would mimic the shape, location, and spread of the smooth pdf. It does not.\n\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-005-grid-simulation-with-posterior}\n: Histogram of the grid simulation with Posterior PDF\n::::::\n:::\n::::{.my-r-code-container}\n\n::: {.cell}\n\n```{.r .cell-code}\n# Histogram of the grid simulation with posterior pdf\nggplot2::ggplot(post_sample, ggplot2::aes(x = pi_grid)) + \n  ggplot2::geom_histogram(\n      ggplot2::aes(y = ggplot2::after_stat(density)), \n        color = \"white\",\n        bins = 30,\n        boundary = 0) +   ## added to ensure that bins start at 0\n  ggplot2::stat_function(\n      fun = dbeta, \n      args = list(11, 3),\n      color = \"darkred\",\n      linewidth = 1) + \n  ggplot2::xlim(0, 1)\n```\n\n::: {.cell-output-display}\n![A grid approximation of the posterior pdf of  π using only 6 grid values. The actual pdf is represented by the curve.](006-approximating-posterior_files/figure-html/fig-grid-simulation-with-posterior-1.png){#fig-grid-simulation-with-posterior width=384}\n:::\n:::\n\n\n\n\n::::\n:::::\n\n::: {.callout-note #nte-006-remove-warning}\n###### Warning about values outside of range\n\nThe last line of the code in book (`lims(x = c(0, 1))`) produces a warning:\n\n> Removed 2 rows containing missing values or values outside the scale range (`geom_bar()`).\n\nMy first solution was to use instead `coord_cartesian(xlim = c(0, 1)` to remove this warning. Although this worked in @fig-006-grid-simulation-101-values it didn't work here:\n\n**Why it works in @fig-006-grid-simulation-101-values**\n\n- `xlim()` and `ylim()` filter the data before plotting, removing rows that fall outside the range, which triggers the warning. \n- `coord_cartesian()` zooms the plot without removing data, so no rows are dropped and the warning is avoided.\n\n**Why it didn't work in @fig-grid-simulation-with-posterior**\n\n`ggplot2::coord_cartesian(xlim = c(0, 1))` zooms into the plot **after** the histogram bins are calculated, so the binning is based on the full data range, not just [0,1].  This can distort the appearance of the histogram, even if your data (pi_grid) is already within [0,1]\n\nHere the solution is to add the histogram parameter `boundary = 0`. This ensures that bins start at 0.\n\n:::\n\nInstead of chopping up the 0-to-1 continuum of possible $˜pi$ values into a grid of only 6 values, let’s try a more reasonable grid of **101 values**: $\\pi \\in \\{0, 0.01, 0.02, . . . , 0.99, 1\\}$. The first 3 grid approximation steps using this refined grid are performed below:\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-006-grid-approximation-101-values}\n: Numbered R Code Title\n::::::\n:::\n::::{.my-r-code-container}\n\n::: {.cell}\n\n```{.r .cell-code}\n# Step 1: Define a grid of 101 pi values\ngrid_data  <- tibble::tibble(\n    pi_grid = base::seq(from = 0, to = 1, length = 101)\n    )\n\n# Step 2: Evaluate the prior & likelihood at each pi\ngrid_data <- grid_data |>  \n  dplyr::mutate(prior = stats::dbeta(pi_grid, 2, 2),\n         likelihood = stats::dbinom(9, 10, pi_grid))\n\n\n# Step 3: Approximate the posterior\ngrid_data <- grid_data |>  \n  dplyr::mutate(unnormalized = likelihood * prior,\n         posterior = unnormalized / base::sum(unnormalized))\n\nggplot2::ggplot(grid_data, \n        ggplot2::aes(x = pi_grid, y = posterior)) + \n  ggplot2::geom_point() + \n  ggplot2::geom_segment(\n        ggplot2::aes(\n            x = pi_grid, \n            xend = pi_grid, \n            y = 0, \n            yend = posterior)\n        )\n```\n\n::: {.cell-output-display}\n![The discretized posterior pdf of π at 101 grid values.](006-approximating-posterior_files/figure-html/fig-grid-approximation-101-values-1.png){#fig-grid-approximation-101-values width=384}\n:::\n:::\n\n\n::::\n:::::\n\nThe resulting discretized posterior pdf is quite smooth, especially in comparison to the rigid approximation when we only used 6 grid values in @fig-006-grid-approx-posterior.\n\nFinally, in step 4 of the grid approximation, we sample 10,000 draws from the discretized posterior pdf:\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-006-grid-simulation-101-values}\n: Grid approximation of the posterior pdf of π using 101 grid values.\n::::::\n:::\n::::{.my-r-code-container}\n\n::: {.cell}\n\n```{.r .cell-code}\n# Set the seed\nset.seed(84735)\n\n# Step 4: sample from the discretized posterior\npost_sample <- dplyr::slice_sample(grid_data, n = 10000, \n                        weight_by = posterior, replace = TRUE)\n\nggplot2::ggplot(post_sample, ggplot2::aes(x = pi_grid)) + \n    ggplot2::geom_histogram(\n          ggplot2::aes(y = ggplot2::after_stat(density)), \n          color = \"white\", \n          binwidth = 0.05) + \n    ggplot2::stat_function(\n        fun = dbeta, \n        args = list(11, 3),\n        color = \"darkred\",\n        linewidth = 1) + \n    ggplot2::coord_cartesian(xlim = c(0, 1))\n```\n\n::: {.cell-output-display}\n![A grid approximation of the posterior pdf of π using 101 grid values. The actual pdf is represented by the curve.](006-approximating-posterior_files/figure-html/fig-006-grid-simulation-101-values-1.png){#fig-006-grid-simulation-101-values width=384}\n:::\n:::\n\n\n::::\n:::::\n\n@fig-006-grid-simulation-101-values displays a histogram of the resulting sample values. The shape, location, and spread of these values mimic those of the true target posterior pdf $f (\\pi \\mid y)$, represented by the smooth curve.\n\nTake a step back to appreciate what we’ve just accomplished. We’ve taken an independent sample from a discretized approximation of the posterior pdf $f (\\pi \\mid y)$ that’s defined only on a grid of $\\pi$ values. The algorithm is pretty intuitive and didn’t require advanced programming skills to implement. Most of all, the result was a sample that behaves much like a random sample taken directly from $f (\\pi \\mid y)$ itself. \n\nThus, grid approximation can be a lifeline in scenarios in which the posterior is intractable, providing an approximation that’s nearly indistinguishable from the “real thing.”\n\n### Gamma-Poisson example\n\n#### Definition\n\nFor practice, let’s apply the grid approximation technique to simulate the posterior of another Bayesian model, this time a Gamma-Poisson. Let $Y$ be the number of events that occur in a one-hour period, where events occur at an average rate of $\\lambda$ per hour. Further, suppose we collect two data points ($Y_1, Y_2$) and place a $\\text{Gamma}(3, 1)$ prior on $\\lambda$:\n\n$$\n\\begin{align*}\nY_i \\mid \\lambda &\\overset{\\text{ind}}{\\sim} Pois(λ) \\\\ \n\\lambda &\\sim \\text{Gamma}(3, 1)\n\\end{align*}\n$$ {#eq-006-gamma-poisson-example}\n\n\nIf we observe $Y_1 = 2$ events in the first one-hour observation period and $Y_2 = 8$ in the next, then by our work in @sec-chap-005 specifically @eq-005-gamma-poisson-model, the updated posterior model of $\\lambda$ is Gamma with parameters 13 ($s + \\sum{Y} = 3 + 10$) and 3 ($r + n = 1 + 2$):\n\n$$\n\\lambda \\mid ((Y_1, Y_2) = (2, 8)) \\sim \\text{Gamma}(13, 3)\n$$ {#eq-006-gamma-poisson-example2}\n\n(There is a typo in the book: $Y_2 = 8$ and not $3$ as in the book.)\n\n#### Approximation\n\n##### Step 1: Determine grid\n\nTo simulate this posterior using grid approximation, **Step 1** is to specify a discrete grid of reasonable $\\lambda$ values. Unlike the π parameter in the Beta-Binomial which is restricted to the finite 0-to-1 interval, the Poisson parameter $\\lambda$ can technically take on any non-negative real value ($\\lambda \\in [0, \\infty)$). \n\nHowever, in a plot of the Gamma prior pdf and Poisson likelihood function it appears that, though possible, values of $\\lambda$ beyond 15 are implausible (@fig-006-gamma-poisson-prior-likelihood).\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-006-gamma-poisson-prior-likelihood}\n:  Plot of the Gamma prior pdf and Poisson likelihood function\n::::::\n:::\n::::{.my-r-code-container}\n\n::: {.cell}\n\n```{.r .cell-code}\nbayesrules::plot_gamma_poisson(\n    shape = 3,\n    rate = 1,\n    sum_y = 10,\n    n = 2,\n    posterior = FALSE\n)\n```\n\n::: {.cell-output-display}\n![A Gamma prior pdf and scaled Poisson likelihood function for λ.](006-approximating-posterior_files/figure-html/fig-006-gamma-poisson-prior-likelihood-1.png){#fig-006-gamma-poisson-prior-likelihood width=672}\n:::\n:::\n\n\n::::\n:::::\n\n##### Step 2: Grid approximation quiz\n\nWith this in mind, we’ll set up a discrete grid of $\\lambda$ values between 0 and 15, essentially truncating the posterior’s tail. Before completing the corresponding grid approximation together, we encourage you to challenge yourself by first trying the quiz below.\n\n\n:::::{.my-assessment}\n:::{.my-assessment-header}\n:::::: {#cor-006-quiz-grid-approx}\n: Construct a grid approximation of the Gamma-Poisson posterior\n::::::\n:::\n::::{.my-assessment-container}\n\nFill in the code below to construct a grid approximation of the Gamma-Poisson posterior corresponding to @eq-006-gamma-poisson-example. In doing so, use a grid of 501 $\\lambda$ values between 0 and 15.\n\nIf you have difficulties then use the step-by-step example in @sec-006-approximation for the Beta-Binomial as a template changing those parts that are different for the Gamma-Poisson.\n\n::: {#big-text style=\"font-size: 110%\"}\n**Step 1: Define a grid of 501 lambda values**\n:::\n\n::: {#monospace-text style=\"font-family: 'Fira Code', monospace\"}\ngrid_data <- data.frame(    \n&nbsp;&nbsp;lambda_grid = seq(   \n&nbsp;&nbsp;&nbsp;&nbsp;from = <input class='webex-solveme nospaces' size='3' data-answer='[\"0\"]'/>,     \n&nbsp;&nbsp;&nbsp;&nbsp;to = <input class='webex-solveme nospaces' size='3' data-answer='[\"15\"]'/>,      \n&nbsp;&nbsp;&nbsp;&nbsp;length = <input class='webex-solveme nospaces' size='3' data-answer='[\"501\"]'/>)    \n&nbsp;&nbsp;&nbsp;&nbsp;)\n:::\n\n\n::: {#big-text style=\"font-size: 110%\"}\n**Step 2: Evaluate the prior & likelihood at each lambda**\n:::\n\n::: {#monospace-text style=\"font-family: 'Fira Code', monospace\"}\ngrid_data <- grid_data  |>      \n&nbsp;&nbsp;<input class='webex-solveme nospaces' size='10' data-answer='[\"mutate\"]'/>(prior =       \n&nbsp;&nbsp;&nbsp;&nbsp;dgamma(<input class='webex-solveme nospaces' size='10' data-answer='[\"grid_data\"]'/>,     \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input class='webex-solveme nospaces' size='10' data-answer='[\"3\"]'/>,      \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input class='webex-solveme nospaces' size='10' data-answer='[\"1\"]'/>)),    \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;likelihood = dpois(<input class='webex-solveme nospaces' size='10' data-answer='[\"2\"]'/>,<input class='webex-solveme nospaces' size='10' data-answer='[\"lambda_grid\"]'/>) * \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dpois(<input class='webex-solveme nospaces' size='10' data-answer='[\"8\"]'/>, <input class='webex-solveme nospaces' size='10' data-answer='[\"lambda_grid\"]'/>))\n:::\n\n::: {#big-text style=\"font-size: 110%\"}\n**Step 3: Approximate the posterior**\n:::\n\n::: {#monospace-text style=\"font-family: 'Fira Code', monospace\"}\ngrid_data <- grid_data  |>       \n&nbsp;&nbsp;<input class='webex-solveme nospaces' size='10' data-answer='[\"mutate\"]'/>(unnormalized = <input class='webex-solveme nospaces' size='10' data-answer='[\"likelihood\"]'/> *  <input class='webex-solveme nospaces' size='10' data-answer='[\"prior\"]'/>,         \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;posterior = <input class='webex-solveme nospaces' size='10' data-answer='[\"unnormalized\"]'/> / <input class='webex-solveme nospaces' size='10' data-answer='[\"sum(unnormalized)\"]'/>))\n:::\n        \n**Set the seed**\n\n::: {#monospace-text style=\"font-family: 'Fira Code', monospace\"}\nset.seed(84735)  \n:::\n\n::: {#big-text style=\"font-size: 110%\"}\n**Step 4: sample from the discretized posterior**\n:::\n\n\n::: {#monospace-text style=\"font-family: 'Fira Code', monospace\"}\npost_sample <- slice_sample(<input class='webex-solveme nospaces' size='10' data-answer='[\"grid_data\"]'/>, n = <input class='webex-solveme nospaces' size='10' data-answer='[\"grid_data\"]'/>,        \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;weight_by = <input class='webex-solveme nospaces' size='10' data-answer='[\"posterior\"]'/>, replace = <input class='webex-solveme nospaces' size='10' data-answer='[\"TRUE\"]'/>)\n:::\n\n\n::::\n:::::\n\n\nCheck out the complete code of @cor-006-quiz-grid-approx. Much of this is the same as it was for the Beta-Binomial model. There are two key differences. \n\n1. First, we use `dgamma()` and `dpois()` instead of `dbeta()` and `dbinom()` to evaluate the prior pdf and likelihood function of $\\lambda$. \n2. Second, since we have a sample of two data points $(Y_1, Y_2) = (2, 8)$, the Poisson likelihood function of $\\lambda$ must be calculated by the product of the marginal Poisson pdfs, $L(\\lambda \\mid y_1, y_2) = f (y_1, y2 \\mid \\lambda) =  f (y_1 \\mid \\lambda)f (y_2 \\mid \\lambda)$.\n\n##### Step 2: Grid approximation exercise\n\nIf you have successfully filled in the quiz try now a more complex exercise. Try it out without looking into @cor-006-quiz-grid-approx. In contrast to @cor-006-quiz-grid-approx you have to fill in all the gaps before you can run the (real) code and see if it gets as output the structure of the `post_sample`.\n\n\nRemember: Use a grid of 501 with values between 0 and 15 applying the formula @eq-006-gamma-poisson-example resp. @eq-006-gamma-poisson-example2:\n\n$$\n\\begin{align*}\nY_i \\mid \\lambda &\\overset{\\text{ind}}{\\sim} Pois(λ) \\\\ \n\\lambda &\\sim \\text{Gamma}(3, 1) \\\\\n\\\\\n\\lambda \\mid ((Y_1, Y_2) = (2, 8)) &\\sim \\text{Gamma}(13, 3).\n\\end{align*}\n$$\n**Construct a grid approximation of the Gamma-Poisson posterior corresponding to @prp-006-detailed-steps-of-grid-approximation.**\n\n\n::: {.cell exercise='ex-1'}\n```{webr}\n#| label: construct-grid-approximation-gamma-poisson-posterior\n#| exercise: ex-1\n\n# Step 1: Define a grid of 501 lambda values\ngrid_data   <- data.frame(\n    lambda_grid = seq(from = ___, to = ___, length = ___)\n    )\n\n# Step 2: Evaluate the prior & likelihood at each lambda\ngrid_data <- grid_data |> \n  dplyr::___(prior = dgamma(___, ___, ___),\n         likelihood = dpois(___, ___) * dpois(___, ___)\n      )\n\n# Step 3: Approximate the posterior\ngrid_data <- grid_data |>  \n  dplyr::___(unnormalized = ___ * ___,\n         posterior = ___ / ___)\n     )\n\n# Set the seed\nset.seed(84735)\n\n# Step 4: sample from the discretized posterior\npost_sample <- dplyr::slice_sample(___, n = ___, \n                        weight_by = ___, replace = ___)\n\ndplyr::glimpse(post_sample)\n```\n:::\n\n\nCompare your result with the following code and output:\n\n\n\n::: {.cell}\n\n```{#lst-construct-grid-approximation-gamma-poisson-posterior .r .cell-code  lst-cap=\"Show the code for the above exercise\"}\n# Step 1: Define a grid of 501 lambda values\ngrid_data   <- data.frame(lambda_grid = seq(from = 0, to = 15, length = 501))\n\n# Step 2: Evaluate the prior & likelihood at each lambda\ngrid_data <- grid_data |> \n  dplyr::mutate(prior = dgamma(lambda_grid, 3, 1),\n         likelihood = dpois(2, lambda_grid) * dpois(8, lambda_grid))\n\n# Step 3: Approximate the posterior\ngrid_data <- grid_data |> \n  dplyr::mutate(unnormalized = likelihood * prior,\n         posterior = unnormalized / sum(unnormalized))\n\n# Set the seed\nset.seed(84735)\n\n# Step 4: sample from the discretized posterior\npost_sample2 <- dplyr::slice_sample(grid_data, n = 10000, \n                        weight_by = posterior, replace = TRUE)\n\ndplyr::glimpse(post_sample2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Rows: 10,000\n#> Columns: 5\n#> $ lambda_grid  <dbl> 4.23, 4.26, 2.55, 4.92, 4.14, 3.60, 3.24, 5.37, 4.08, 2.1…\n#> $ prior        <dbl> 0.13019223, 0.12814295, 0.25386302, 0.08834284, 0.1364556…\n#> $ likelihood   <dbl> 0.0048163921, 0.0048680663, 0.0008789202, 0.0054908908, 0…\n#> $ unnormalized <dbl> 6.270569e-04, 6.238084e-04, 2.231253e-04, 4.850809e-04, 6…\n#> $ posterior    <dbl> 0.010098295, 0.010045980, 0.003593271, 0.007811875, 0.010…\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n#### Step 2: Grid approximation final\n\nMost importantly, grid approximation again produced a decent approximation of our target posterior:\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-006-grid-approximation-gamma-poisson-example}\n: Grid approximation of the posterior pdf of $\\lambda$ using 501 grid values\n::::::\n:::\n::::{.my-r-code-container}\n\n::: {.cell}\n\n```{.r .cell-code}\n# Step 1: Define a grid of 501 lambda values\ngrid_data   <- data.frame(lambda_grid = seq(from = 0, to = 15, length = 501))\n\n# Step 2: Evaluate the prior & likelihood at each lambda\ngrid_data <- grid_data |>  \n  dplyr::mutate(prior = dgamma(lambda_grid, 3, 1),\n         likelihood = dpois(2, lambda_grid) * dpois(8, lambda_grid))\n\n# Step 3: Approximate the posterior\ngrid_data <- grid_data |>  \n  dplyr::mutate(unnormalized = likelihood * prior,\n         posterior = unnormalized / sum(unnormalized))\n\n# Set the seed\nset.seed(84735)\n\n# Step 4: sample from the discretized posterior\npost_sample <- dplyr::slice_sample(grid_data, n = 10000, \n                        weight_by = posterior, replace = TRUE)\n\n# Histogram of the grid simulation with posterior pdf \nggplot2::ggplot(post_sample, ggplot2::aes(x = lambda_grid)) + \n  ggplot2::geom_histogram(\n      ggplot2::aes(y = ggplot2::after_stat(density)), \n            color = \"black\",\n            binwidth = 0.5,\n            boundary = 0) + \n  ggplot2::stat_function(\n      fun = dgamma, \n      args = list(13, 3),\n      linewidth = 1,\n      color = \"darkred\") + \n  ggplot2::lims(x = c(0, 15))\n```\n\n::: {.cell-output-display}\n![A grid approximation of the posterior pdf of λ using 501 grid values. The actual pdf is represented by the red curve.](006-approximating-posterior_files/figure-html/fig-006-grid-approximation-gamma-poisson-example-1.png){#fig-006-grid-approximation-gamma-poisson-example width=384}\n:::\n:::\n\n\n::::\n:::::\n\n\n### Limitation\n\nLimitations in the grid approximation method quickly present themselves as our models get more complicated. For example, by the end of Unit 4 we’ll be working with models that have lots of model parameters $\\theta = (\\theta_1, \\theta_2, . . . , \\theta_k)$. In such settings, grid approximation suffers from the **curse of dimensionality**.\n\nWhen using grid approximation to simulate multivariate posteriors, we need to divide the multidimensional sample space of $\\theta = (\\theta_1, \\theta_2, . . . , \\theta_k)$ into a very, very fine grid in order to prevent big gaps in our approximation. In practice, this might not be feasible. When evaluated on finer and finer grids, the grid approximation method becomes computationally expensive. You can’t merely start the simulation, get up for a cup of coffee, come back, and poof the simulation is done. You might have to start the simulation and go off to a month-long meditation retreat (to practice the patience you’ll need for grid approximation). <a class='glossary' title='Markov chain Monte Carlo (MCMC) methods comprise a class of algorithms for sampling from a probability distribution. By constructing a [markov chain] that has the desired distribution as its equilibrium distribution, one can obtain a sample of the desired distribution by recording states from the chain. The more steps that are included, the more closely the distribution of the sample matches the actual desired distribution. Various algorithms exist for constructing chains. (Wikipedia)'>MCMC</a> methods provide a more flexible alternative.\n\n\n## Markov chains via {rstan}\n\nThe <a class='glossary' title='Markov chain is a stochastic model describing a sequence of possible events in which the probability of each event depends only on the state attained in the previous event.  This defining property is known as the Markov property or memorylessness, meaning the future state depends solely on the current state and not on the sequence of events that preceded it. (Brave-AI)'>Markov chain</a> component of <a class='glossary' title='Markov chain Monte Carlo (MCMC) methods comprise a class of algorithms for sampling from a probability distribution. By constructing a [markov chain] that has the desired distribution as its equilibrium distribution, one can obtain a sample of the desired distribution by recording states from the chain. The more steps that are included, the more closely the distribution of the sample matches the actual desired distribution. Various algorithms exist for constructing chains. (Wikipedia)'>MCMC</a> is named for the Russian mathematician Andrey Markov (1856-1922). The etymology of the Monte Carlo component is more dubious:\n\nAs part of their top secret nuclear weapons project in the 1940s, Stanislav Ulam, John von Neumann, and their collaborators at the Los Alamos National Laboratory used Markov chains to simulate and better understand neutron travel [@roger1987]. The Los Alamos team referred to their work by the code name “Monte Carlo,” a choice said to be inspired by the opulent Monte Carlo casino in the French Riviera. What inspired the link between random simulation methods and casinos? We can’t help you there.\n\nToday, “Markov chain Monte Carlo” refers to the application of Markov chains to simulate probability models using methods pioneered by the Monte Carlo project. In contrast to grid approximation, MCMC simulation methods scale up for more complicated Bayesian models. But this flexibility doesn’t come for free. Like grid approximation samples, **MCMC samples are *not* taken directly from the posterior pdf** $f (\\theta \\mid y)$. Yet unlike grid approximation samples, **MCMC samples aren’t even independent** – each subsequent sample value depends directly upon the previous value. This feature is evoked by the “chain” terminology. \n\nSpecifically, let $\\{\\theta^{(1)}, \\theta^{(2)}, . . . , \\theta^{(N)}\\}$ be an N-length MCMC sample, or **Markov chain**. In  constructing this chain, (2) is drawn from some model that depends upon $\\theta^{(1)}$, $\\theta^{(3)}$ is drawn from some model that depends upon $\\theta^{(2)}$, $\\theta^{(4)}$ is drawn from some model that depends upon $\\theta^{(3)}$, and so on and so on the chain grows. In general, the (i + 1)st chain value $\\theta^{(i+1)} is drawn from a model that depends on data $y$ and the previous chain value $\\theta^{(i)}$ with conditional pdf\n\n$$\nf (\\theta^{(i+1)} \\mid \\theta^{(i)}, y)\n$$\n\nThere are a couple of things to note about this dependence among chain values. First, by the **Markov property**, $\\theta^{(i+1)}$ depends upon the preceding chain values only through the most recent value $\\theta^{(i)}$:  \n\n$$\nf (\\theta^{(i+1)} \\mid \\theta^{(1)}, \\theta^{(2)}, . . . , \\theta^{(i)}, y) = f (\\theta^{(i+1)} \\mid \\theta^{(i)}, y)\n$$\n\nFor example, since $\\theta^{(i+i)}$ depends on $\\theta^{(i)}$ which depends on $\\theta^{(i-1)}$, it’s also true that $\\theta^{(i+i)}$ depends on $\\theta^{(i-1)}$. However, if we know $\\theta^{(i)}$, then $\\theta^{(i-1)}$ is of no consequence to $\\theta^{(i+1)}$ – the only information we need to simulate $\\theta^{(i+1)}$ is the value of $\\theta^{(i)}$. Further, each chain value can be drawn from a different model, and none of these models are the target posterior. That is, the pdf from which a Markov chain value is simulated is not equivalent to the posterior pdf: \n\n$$\nf (\\theta^{(i+1)} \\mid \\theta^{(i)}, y) \\ne f (\\theta^{(i+1)} \\mid y)\n$$\n\n:::::{.my-experiment}\n:::{.my-experiment-header}\n:::::: {#def-006-markov-chain}\n: Markov Chain Monte Carlo (MCMC)\n::::::\n:::\n::::{.my-experiment-container}\n\n<a class='glossary' title='Markov chain Monte Carlo (MCMC) methods comprise a class of algorithms for sampling from a probability distribution. By constructing a [markov chain] that has the desired distribution as its equilibrium distribution, one can obtain a sample of the desired distribution by recording states from the chain. The more steps that are included, the more closely the distribution of the sample matches the actual desired distribution. Various algorithms exist for constructing chains. (Wikipedia)'>MCMC</a> simulation produces a chain of N **dependent** $\\theta$ values,\n\\theta^{(1)}, \\theta^{(2)}, . . . , \\theta^{(N)}, which are **not** drawn from the posterior pdf $f (\\theta \\mid y)$.\n\n::::\n:::::\n\nIt likely seems strange to approximate the posterior using a dependent sample that’s not even taken from the posterior. But mathemagically, with reasonable MCMC *algorithms*, it can work. The rub is that these algorithms have a steeper learning curve than the grid approximation technique.\n\n:::::{.my-resource}\n:::{.my-resource-header}\n:::::: {#lem-006-mcmc-resources}\n: MCMC resources\n::::::\n:::\n::::{.my-resource-container}\n\nWe provide a glimpse into the details of the MCMC workings in @sec-chap-007. \n\nThough a review of @sec-chap-007 and a firm grasp of these details would be ideal, there’s a growing number of MCMC computing resources that can do the heavy lifting for us:\n\n- In this book, we’ll conduct MCMC simulation using the {**rstan**} package [@rstan] which combines the power of R with the Stan engine. You’ll get into the nitty gritty of {**rstan**} in this chapter, building up the code line by line and thereby gaining familiarity with the key elements of an {**rstan**} simulation. \n- Starting in @sec-chap-009, you will utilize the complementary {**rstanarm**} package [@rstanarm], which provides shortcuts for simulating a broad framework of Bayesian *applied regression models* (arm).\n\n::::\n:::::\n\n\n### Beta-Binomial example\n\nThere are two essential steps to all rstan analyses: \n\n(1) **define the Bayesian model structure** in {**rstan**} notation and \n(2) **simulate the posterior**. \n\n#### Step 1: Define model structure\n\nLet’s examine these steps in the context of the Beta-Binomial model defined by @eq-006-beta-binomial-example, starting with step 1. In defining the structure of this model, we must specify the three aspects upon which it depends:  \n\n::: {#big-text style=\"font-size: 120%\"}\n**data** \n:::\n \nData $Y$ is the observed number of successes in $10$ trials. Since {**rstan**} isn’t a mind reader, we must specify that $Y$ is an integer between $0$ and $10$.\n\n::: {#big-text style=\"font-size: 120%\"}\n**parameters** \n:::\n  \nThe model depends upon parameter $\\pi$, or `pi` in {**rstan**} notation. We must specify that $\\pi$ can be any real number between $0$ and $1$.  \n\n::: {#big-text style=\"font-size: 120%\"}\n**model** \n:::\n  \nThe model is defined by the $\\text{Bin}(10, \\pi)$ model for data $Y$ and the $\\text{Beta}(2, 2)$ prior for $\\pi$. We specify these using `binomial()` and `beta()`.  Below we translate this Beta-Binomial structure into {**rstan**} syntax and store it as the character string `bb_model`. We encourage you to pause and examine the code, noting how it matches up with the three aspects above.\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-006-beta-binomial-rstan-syntax}\n: Step 1: Define Beta-Binomial in {rstan}-syntax\n::::::\n:::\n::::{.my-r-code-container}\n\n::: {.cell}\n\n```{#lst-006-beta-binomial-rstan-syntax .r .cell-code  lst-cap=\"Step 1: Define Beta-Binomial in {**rstan**}-syntax\" code-fold=\"false\"}\n# STEP 1: DEFINE the model\nbb_model <- \"\n  data {\n    int<lower = 0, upper = 10> Y;\n  }\n  parameters {\n    real<lower = 0, upper = 1> pi;\n  }\n  model {\n    Y ~ binomial(10, pi);\n    pi ~ beta(2, 2);\n  }\n\"\n```\n:::\n\n\n::::\n:::::\n\n#### Step 2: Simulate the posterior\n\nIn **step 2**, we *simulate* the posterior using the `rstan::stan()` function. Very loosely speaking, `rstan::stan()` designs and runs an MCMC algorithm to produce an approximate sample from the Beta-Binomial posterior.\n\n::: {.callout-warning #wrn-006-stan-slow}\n###### Simulation is quite slow for each new model\n\nSince `rstan::stan()` has to do the double duty of identifying an appropriate MCMC algorithm for simulating the given model, and then applying this algorithm to our data, the simulation will be quite slow for each new model. (About 15 seconds on Apple M4 Pro, 48 GB memory, Tahoe 26.3.)\n\n:::\n\nNote that `rstan::stan()` requires two types of arguments. \n\n1. First, we must specify the **model information** by:  \n\n- `model_code` = the character string defining the model (here `bb_model`) \n- `data` = a list of the observed data (here `Y = 9`).  \n\n2. Second, we must specify the desired **Markov chain information** using three additional arguments:  \n\n- The `chains` argument specifies how many parallel Markov chains to run. We run four chains here, thus obtain four distinct samples of $\\pi$ values. We discuss this choice in Section 6.3.  \n- The `iter` argument specifies the desired number of iterations in, or *length* of, each Markov chain. By default, the first half of these iterations are thrown out as “burn-in” or “warm-up” samples (see below for details). The second half are kept as the final Markov chain sample.  \n- To set the random number generating seed for an {**rstan**} simulation, we utilize the `seed` argument *within* the `rstan::stan()` function. \n\nThe result, stored in `bb_sim`, is a `stanfit` object. This object includes four parallel Markov chains run for 10,000 iterations each. After tossing out the first 5,000 iterations of all four chains, we end up with four separate Markov chain samples of size 5,000, or a combined **Markov chain sample size** of 20,000.\n\nThe first four $\\pi$ values for each of the four parallel chains are extracted and shown here:\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-006-beta-binomial-example-simulation}\n: Step 2: Simulation of the Beta-Binomial example\n::::::\n:::\n::::{.my-r-code-container}\n\n::: {#tbl-006-beta-binomial-example-simulation .cell tbl-cap='Step 2: Simulation of the Beta-Binomial example'}\n\n```{#lst-006-beta-binomial-example-simulation .r .cell-code  lst-cap=\"Step 2: Simulation of the Beta-Binomial example\" code-fold=\"false\"}\n# STEP 2: SIMULATE the posterior\nbb_sim <- rstan::stan(model_code = bb_model, data = list(Y = 9), \n               chains = 4, iter = 5000*2, seed = 84735)\n\nas.array(bb_sim, pars = \"pi\") |> \n  head(4) |> \n    knitr::kable()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> SAMPLING FOR MODEL 'anon_model' NOW (CHAIN 1).\n#> Chain 1: \n#> Chain 1: Gradient evaluation took 5e-06 seconds\n#> Chain 1: 1000 transitions using 10 leapfrog steps per transition would take 0.05 seconds.\n#> Chain 1: Adjust your expectations accordingly!\n#> Chain 1: \n#> Chain 1: \n#> Chain 1: Iteration:    1 / 10000 [  0%]  (Warmup)\n#> Chain 1: Iteration: 1000 / 10000 [ 10%]  (Warmup)\n#> Chain 1: Iteration: 2000 / 10000 [ 20%]  (Warmup)\n#> Chain 1: Iteration: 3000 / 10000 [ 30%]  (Warmup)\n#> Chain 1: Iteration: 4000 / 10000 [ 40%]  (Warmup)\n#> Chain 1: Iteration: 5000 / 10000 [ 50%]  (Warmup)\n#> Chain 1: Iteration: 5001 / 10000 [ 50%]  (Sampling)\n#> Chain 1: Iteration: 6000 / 10000 [ 60%]  (Sampling)\n#> Chain 1: Iteration: 7000 / 10000 [ 70%]  (Sampling)\n#> Chain 1: Iteration: 8000 / 10000 [ 80%]  (Sampling)\n#> Chain 1: Iteration: 9000 / 10000 [ 90%]  (Sampling)\n#> Chain 1: Iteration: 10000 / 10000 [100%]  (Sampling)\n#> Chain 1: \n#> Chain 1:  Elapsed Time: 0.01 seconds (Warm-up)\n#> Chain 1:                0.011 seconds (Sampling)\n#> Chain 1:                0.021 seconds (Total)\n#> Chain 1: \n#> \n#> SAMPLING FOR MODEL 'anon_model' NOW (CHAIN 2).\n#> Chain 2: \n#> Chain 2: Gradient evaluation took 0 seconds\n#> Chain 2: 1000 transitions using 10 leapfrog steps per transition would take 0 seconds.\n#> Chain 2: Adjust your expectations accordingly!\n#> Chain 2: \n#> Chain 2: \n#> Chain 2: Iteration:    1 / 10000 [  0%]  (Warmup)\n#> Chain 2: Iteration: 1000 / 10000 [ 10%]  (Warmup)\n#> Chain 2: Iteration: 2000 / 10000 [ 20%]  (Warmup)\n#> Chain 2: Iteration: 3000 / 10000 [ 30%]  (Warmup)\n#> Chain 2: Iteration: 4000 / 10000 [ 40%]  (Warmup)\n#> Chain 2: Iteration: 5000 / 10000 [ 50%]  (Warmup)\n#> Chain 2: Iteration: 5001 / 10000 [ 50%]  (Sampling)\n#> Chain 2: Iteration: 6000 / 10000 [ 60%]  (Sampling)\n#> Chain 2: Iteration: 7000 / 10000 [ 70%]  (Sampling)\n#> Chain 2: Iteration: 8000 / 10000 [ 80%]  (Sampling)\n#> Chain 2: Iteration: 9000 / 10000 [ 90%]  (Sampling)\n#> Chain 2: Iteration: 10000 / 10000 [100%]  (Sampling)\n#> Chain 2: \n#> Chain 2:  Elapsed Time: 0.01 seconds (Warm-up)\n#> Chain 2:                0.011 seconds (Sampling)\n#> Chain 2:                0.021 seconds (Total)\n#> Chain 2: \n#> \n#> SAMPLING FOR MODEL 'anon_model' NOW (CHAIN 3).\n#> Chain 3: \n#> Chain 3: Gradient evaluation took 0 seconds\n#> Chain 3: 1000 transitions using 10 leapfrog steps per transition would take 0 seconds.\n#> Chain 3: Adjust your expectations accordingly!\n#> Chain 3: \n#> Chain 3: \n#> Chain 3: Iteration:    1 / 10000 [  0%]  (Warmup)\n#> Chain 3: Iteration: 1000 / 10000 [ 10%]  (Warmup)\n#> Chain 3: Iteration: 2000 / 10000 [ 20%]  (Warmup)\n#> Chain 3: Iteration: 3000 / 10000 [ 30%]  (Warmup)\n#> Chain 3: Iteration: 4000 / 10000 [ 40%]  (Warmup)\n#> Chain 3: Iteration: 5000 / 10000 [ 50%]  (Warmup)\n#> Chain 3: Iteration: 5001 / 10000 [ 50%]  (Sampling)\n#> Chain 3: Iteration: 6000 / 10000 [ 60%]  (Sampling)\n#> Chain 3: Iteration: 7000 / 10000 [ 70%]  (Sampling)\n#> Chain 3: Iteration: 8000 / 10000 [ 80%]  (Sampling)\n#> Chain 3: Iteration: 9000 / 10000 [ 90%]  (Sampling)\n#> Chain 3: Iteration: 10000 / 10000 [100%]  (Sampling)\n#> Chain 3: \n#> Chain 3:  Elapsed Time: 0.01 seconds (Warm-up)\n#> Chain 3:                0.01 seconds (Sampling)\n#> Chain 3:                0.02 seconds (Total)\n#> Chain 3: \n#> \n#> SAMPLING FOR MODEL 'anon_model' NOW (CHAIN 4).\n#> Chain 4: \n#> Chain 4: Gradient evaluation took 0 seconds\n#> Chain 4: 1000 transitions using 10 leapfrog steps per transition would take 0 seconds.\n#> Chain 4: Adjust your expectations accordingly!\n#> Chain 4: \n#> Chain 4: \n#> Chain 4: Iteration:    1 / 10000 [  0%]  (Warmup)\n#> Chain 4: Iteration: 1000 / 10000 [ 10%]  (Warmup)\n#> Chain 4: Iteration: 2000 / 10000 [ 20%]  (Warmup)\n#> Chain 4: Iteration: 3000 / 10000 [ 30%]  (Warmup)\n#> Chain 4: Iteration: 4000 / 10000 [ 40%]  (Warmup)\n#> Chain 4: Iteration: 5000 / 10000 [ 50%]  (Warmup)\n#> Chain 4: Iteration: 5001 / 10000 [ 50%]  (Sampling)\n#> Chain 4: Iteration: 6000 / 10000 [ 60%]  (Sampling)\n#> Chain 4: Iteration: 7000 / 10000 [ 70%]  (Sampling)\n#> Chain 4: Iteration: 8000 / 10000 [ 80%]  (Sampling)\n#> Chain 4: Iteration: 9000 / 10000 [ 90%]  (Sampling)\n#> Chain 4: Iteration: 10000 / 10000 [100%]  (Sampling)\n#> Chain 4: \n#> Chain 4:  Elapsed Time: 0.01 seconds (Warm-up)\n#> Chain 4:                0.011 seconds (Sampling)\n#> Chain 4:                0.021 seconds (Total)\n#> Chain 4:\n```\n\n\n:::\n\n::: {.cell-output-display}\n\n\n| chain:1.pi| chain:2.pi| chain:3.pi| chain:4.pi|\n|----------:|----------:|----------:|----------:|\n|  0.8278040|  0.7523560|  0.6386998|  0.9627572|\n|  0.9087546|  0.8922386|  0.6254761|  0.9413518|\n|  0.6143859|  0.8682356|  0.7222360|  0.9489624|\n|  0.8462156|  0.8792812|  0.8100192|  0.9413812|\n\n\n:::\n:::\n\n\n::::\n:::::\n\n\nIt’s important to remember that these **Markov chain values are NOT a random sample from the posterior and are NOT independent**. Rather, each of the four parallel chains forms a dependent 5,000 length Markov *chain* of $\\pi$ values, $(\\pi^{(1)}, \\pi^{(2)}, . . . , \\pi^{(5000)})$. \n\nFor  example, in iteration 1, `chain:1` starts at a value of roughly $\\pi^{(1)}$ = 0.827804. The value at iteration 2, $\\pi^{(2)}$, depends upon $\\pi^{(1)}$. In this case the chain moves from 0.827804 to 0.9087546. Similarly, the chain moves from 0.9087546 to 0.6143859, from 0.6143859 to 0.8462156, and so on. Thus, the chain traverses the sample space or range of posterior plausible $\\pi$ values. \n\nA Markov chain trace plot illustrates this traversal, plotting the $\\pi$ value (y-axis) in each iteration (x-axis). We use the `mcmc_trace()` function in the {**bayesplot**} package [@bayesplot] to construct the trace plots of all four Markov chains:\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-006-trace-plot-beta-binomial-example}\n: Trace plot for the Beta-Binomial example\n::::::\n:::\n::::{.my-r-code-container}\n\n::: {.cell}\n\n```{.r .cell-code}\nbayesplot::color_scheme_set(\"viridisA\")\nbayesplot::mcmc_trace(bb_sim, pars = \"pi\", size = 0.5)\n```\n\n::: {.cell-output-display}\n![Trace plots of the four parallel Markov chains of π for the Beta_Binomial example](006-approximating-posterior_files/figure-html/fig-006-trace-plot-beta-binomial-example-1.png){#fig-006-trace-plot-beta-binomial-example width=672}\n:::\n:::\n\n\n::::\n:::::\n\n::: {.callout-note #nte-006-trace-plot}\n###### Many parameters\n\nThere are many parameters available for `bayesplot::mcmcm_trace()` that I do not understand (yet). I have experimented with two parameters:\n\n- the line width (aka `size`): In the book is recommended 0.1,. Default value is 0.5 which gives in my opinion a trace plot that is better visible and interpretable.\n- the color scheme: This is actually a different function `color_scheme_set()` but can be used in conjunction with `bayesplot::mcmcm_trace()` to improve the visibility of the trace plot.\n:::\n\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-006-trace-plot-first-iterations}\n: Trace plot with the first 20 resp. 200 iterations\n::::::\n:::\n::::{.my-r-code-container}\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extract all chains as a 3D array [iterations, chains, parameters]\nchains_array <- as.array(bb_sim)\n\n# Create a data frame from the first 20 iterations of chain 1\nchain1_df_20 <- data.frame(\n  iteration = 1:20,\n  pi        = chains_array[1:20, 1, \"pi\"]\n)\n\n# Create a data frame from the first 200 iterations of chain 1\nchain1_df_200 <- data.frame(\n  iteration = 1:200,\n  pi        = chains_array[1:200, 1, \"pi\"]\n)\n\n# Plot the first 20 iterations\np_20 <- ggplot2::ggplot(chain1_df_20, \n                ggplot2::aes(x = iteration, y = pi)) +\n  ggplot2::geom_line(linewidth = 0.5) +\n  ggplot2::labs(\n    title = \"Trace plot: Chain 1 (first 20 iterations)\",\n    x     = \"Iteration\",\n    y     = expression(pi)\n  )\n\n# Plot the first 200 iterations\np_200 <- ggplot2::ggplot(chain1_df_200, \n                ggplot2::aes(x = iteration, y = pi)) +\n  ggplot2::geom_line(linewidth = 0.5) +\n  ggplot2::labs(\n    title = \"Trace plot: Chain 1 (first 200 iterations)\",\n    x     = \"Iteration\",\n    y     = expression(pi)\n  )\n\n# plot both results side by side\npatchwork:::\"-.ggplot\"(p_20, p_200)\n```\n\n::: {.cell-output-display}\n![A trace plot of the first 20 iterations (left) and 200 iterations (right) of the first Beta-Binomial Markov chain.](006-approximating-posterior_files/figure-html/fig-trace-plot-first-iterations-1.png){#fig-trace-plot-first-iterations width=672}\n:::\n:::\n\n\n\n::::\n:::::\n\n@fig-trace-plot-first-iterations zooms in on the trace plot of chain 1. In the first 20 iterations (left), the chain largely explores values between 0.61 and 0.91. After 200 iterations (right), the Markov chain has started to explore new territory, traversing a wider range of values between 0.40 and 0.96. Both trace plots also exhibit evidence of the slight dependence among the Markov chain values, places where the chain tends to float up for multiple iterations and then down for multiple iterations.\n\nMarking the *sequence* of the chain values, the trace plots in @fig-trace-plot-first-iterations illuminate the Markov chains’ **longitudinal** behavior. We also want to examine the **distribution** of the values these chains visit along their journey, ignoring the order of these visits. \n\nThe histogram and density plot in Figure 6.10 provide a snapshot of this distribution for the combined 20,000 chain values, 5,000 from each of the four separate chains. Notice the important punchline here: the distribution of the Markov chain values is an excellent approximation of the target Beta(11, 3) posterior model of $\\pi$ (superimposed in black). That’s a relief – that was the whole point.\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-006-plot-combined-chain-values}\n: Plot distribution of the combined 20,000 chain values\n::::::\n:::\n::::{.my-r-code-container}\n\n::: {.cell}\n\n```{.r .cell-code}\n# Histogram of the Markov chain values\nbayesplot::color_scheme_set(\"teal\")\np1 <- bayesplot::mcmc_hist(bb_sim, pars = \"pi\", bins = 30) + \n  bayesplot::yaxis_text(TRUE) + \n  ggplot2::ylab(\"count\")\n\n# Density plot of the Markov chain values\nbayesplot::color_scheme_set(\"teal\")\np2 <- bayesplot::mcmc_dens(bb_sim, pars = \"pi\") + \n  bayesplot::yaxis_text(TRUE) + \n  ggplot2::ylab(\"density\") +\n  ggplot2::stat_function(\n        fun = dbeta, \n        args = list(11, 3),\n        color = \"darkred\",\n        linewidth = 1)\n\n# plot both results side by side\npatchwork:::\"-.ggplot\"(p1, p2)\n```\n\n::: {.cell-output-display}\n![A histogram (left) and density plot (right) of the combined 20,000 Markov chain π values from the 4 parallel chains. The target pdf is superimposed in red.](006-approximating-posterior_files/figure-html/fig-006-plot-combined-chain-values-1.png){#fig-006-plot-combined-chain-values width=672}\n:::\n:::\n\n\n::::\n:::::\n\n### Gamma-Poisson example\n\nFor more practice with {**rstan**} and <a class='glossary' title='Markov chain Monte Carlo (MCMC) methods comprise a class of algorithms for sampling from a probability distribution. By constructing a [markov chain] that has the desired distribution as its equilibrium distribution, one can obtain a sample of the desired distribution by recording states from the chain. The more steps that are included, the more closely the distribution of the sample matches the actual desired distribution. Various algorithms exist for constructing chains. (Wikipedia)'>MCMC</a> simulation, let’s use these tools to approximate the Gamma-Poisson posterior corresponding to @eq-006-gamma-poisson-example upon observing data $(Y_1, Y_2) = (2, 8)$. Recall that this involves two steps:\n\n- In **step 1**, we define the Gamma-Poisson model structure, specifying the three aspects upon which it depends: the `data`, `parameters`, and `model.` \n- In **step 2**, we simulate the posterior. We encourage you to challenge yourself by trying this on your own first. Your code will require two terms you haven’t yet seen, but you might guess how to use: `poisson()` and `gamma()`. Further, your code will incorporate a vector of $(Y_1, Y_2)$ variables and observations as opposed to a single variable $Y$.\n\n### MCMC approximation quiz\n\n:::::{.my-assessment}\n:::{.my-assessment-header}\n:::::: {#cor-006-mcmc-approx-quiz}\n: MCMC approximation of the Gamma-Poisson posterior \n::::::\n:::\n::::{.my-assessment-container}\nFill in the code below to construct an MCMC approximation of the Gamma-Poisson posterior corresponding to @eq-006-gamma-poisson-example. We have seen another example that shows how to fill in gaps in @lst-006-beta-binomial-rstan-syntax and in @lst-006-beta-binomial-example-simulation.\n\nIn doing so, run four parallel chains for 10,000 iterations each (resulting in a sample size of 5,000 per chain).\n\n::: {#big-text style=\"font-size: 110%\"}\n**Step 1: DEFINE the model**\n:::\n\n::: {#monospace-text style=\"font-family: 'Fira Code', monospace\"}\n\ngp_model <- \"     \n&nbsp;&nbsp;data {     \n&nbsp;&nbsp;&nbsp;&nbsp;int<<input class='webex-solveme nospaces' size='10' data-answer='[\"lower = 0\"]'/>> Y[2];             \n&nbsp;&nbsp;}      \n&nbsp;&nbsp;parameters {       \n&nbsp;&nbsp;&nbsp;&nbsp;real<<input class='webex-solveme nospaces' size='10' data-answer='[\"lower = 0\"]'/>> lambda;      \n&nbsp;&nbsp;}       \n&nbsp;&nbsp;model {        \n&nbsp;&nbsp;&nbsp;&nbsp;Y ~ <input class='webex-solveme nospaces' size='10' data-answer='[\"poisson\"]'/>(<input class='webex-solveme nospaces' size='10' data-answer='[\"lambda\"]'/>);     \n&nbsp;&nbsp;&nbsp;&nbsp;lambda ~ <input class='webex-solveme nospaces' size='10' data-answer='[\"gamma\"]'/>(<input class='webex-solveme nospaces' size='3' data-answer='[\"3\"]'/>, <input class='webex-solveme nospaces' size='3' data-answer='[\"1\"]'/>);      \n&nbsp;&nbsp;}     \n\"\n:::\n\n::: {#big-text style=\"font-size: 110%\"}\n**# STEP 2: SIMULATE the posterior**\n:::\n\n::: {#monospace-text style=\"font-family: 'Fira Code', monospace\"}\n\ngp_sim <- <input class='webex-solveme nospaces' size='12' data-answer='[\"stan\",\"rstan::stan\"]'/>(model_code = <input class='webex-solveme nospaces' size='10' data-answer='[\"gp_model\"]'/>, data = list(<input class='webex-solveme nospaces' size='10' data-answer='[\"Y = c(2, 8)\"]'/>),      \n&nbsp;&nbsp;&nbsp;&nbsp;chains = <input class='webex-solveme nospaces' size='3' data-answer='[\"4\"]'/>, iter = <input class='webex-solveme nospaces' size='10' data-answer='[\"5000 * 2\",\"10000\"]'/>, seed = 84735)\n\n:::\n\n::::\n:::::\n\nIn defining the model in **step 1**, take note of the three aspects upon which it depends.  \n\n- **data**  \n  Data Y[2] represents the vector of event counts, $(Y_1, Y_2)$, where the counts can be any non-negative integers in $\\{0, 1, 2, . . .\\}$.  \n- **parameters**  \n  The model depends upon rate parameter $\\lambda$, which can be any non-negative real number.  \n- **model**  \n  The model is defined by the $\\text{Pois}(\\lambda)$ model for data $Y$ and the $\\text{Gamma}(3,1)$ prior for $\\lambda$. We specify these using `poisson()` and `gamma()`.  \n  \nIn **step 2**, we must feed in the vector of both data points, $Y = c(2,8)$.\n\nTry it again. This time with a simulated exercise using real R code:\n\n\n::: {.cell exercise='ex-2'}\n```{webr}\n#| label: define-and-feed-gamma-poisson-example\n#| exercise: ex-2\n\n# STEP 1: DEFINE the model\ngp_model <- \"\n  data {\n    int<___> Y[2];\n  }\n  parameters {\n    real<___> lambda;\n  }\n  model {\n    Y ~ ___(___);\n    lambda ~ ___(___, ___);\n  }\n\"\n\n# STEP 2: SIMULATE the posterior\ngp_sim <- rstan::___(model_code = ___, data = list(___), \n               chains = ___, iter = ___, seed = 84735)\n```\n:::\n\n\nCompare your solution with the following code:\n\n\n::: {.cell}\n\n```{#lst-006-define-and-feed-gamma-poisson-example2 .r .cell-code  lst-cap=\"Define and feed with data the Gamma-Poisson example\"}\n# STEP 1: DEFINE the model\ngp_model <- \"\n  data {\n    int<lower = 0> Y[2];\n  }\n  parameters {\n    real<lower = 0> lambda;\n  }\n  model {\n    Y ~ poisson(lambda);\n    lambda ~ gamma(3, 1);\n  }\n\"\n\n# STEP 2: SIMULATE the posterior\ngp_sim <- rstan::stan(model_code = gp_model, data = list(Y = c(2,8)), \n               chains = 4, iter = 5000*2, seed = 84735)\n```\n:::\n\n\n\n@fig-006-trace-histogram-density-plots-gamma-poisson-example illustrates the simulation results. First, the trace plots (top) illustrate the paths these chains take through the $\\lambda$ sample space. To this end, note that the $\\lambda$ chain values travel around the rough range from $0$ to $10$, but mostly remain below $7.5$. Further, the histogram and density plot (bottom) provide a better look into the overall distribution of $\\lambda$ Markov chain values. The punchline: this distribution provides an excellent approximation of the $\\text{Gamma}(13,3)$ posterior (superimposed in black).\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-006-trace-histogram-density-plots-gamma-poisson-example}\n: Trace plots, histogram and densitiy plots for the Gamma-Poisson example\n::::::\n:::\n::::{.my-r-code-container}\n\n::: {.cell}\n\n```{.r .cell-code}\n# Trace plots of the 4 Markov chains\np1 <- bayesplot::mcmc_trace(\n  gp_sim, \n  pars = \"lambda\", \n  size = 0.1,\n  ) +\n  ggplot2::scale_y_continuous(breaks = pretty)\n\n\n# Histogram of the Markov chain values\np2 <- bayesplot::mcmc_hist(gp_sim, \n                     pars = \"lambda\",\n                     bins = 30 ) + \n  bayesplot::yaxis_text(TRUE) + \n  ggplot2::labs(y = \"count\")\n\n# Density plot of the Markov chain values\np3 <- bayesplot::mcmc_dens(gp_sim, pars = \"lambda\") +\n  bayesplot::yaxis_text(TRUE) + \n  ggplot2::labs(y = \"density\") +\n  ggplot2::stat_function(\n    fun = dgamma,\n    args = list(shape = 13, rate = 3),\n    color = \"darkred\"\n  )\n\nlibrary(patchwork)\np1 / (p2 | p3)\n```\n\n::: {.cell-output-display}\n![Trace plots of the four parallel Markov chains of λ (top). A histogram and density plot of the 20,000 combined Markov chain values of λ (bottom). The black curve represents the actual posterior pdf of λ.](006-approximating-posterior_files/figure-html/fig-006-trace-histogram-density-plots-gamma-poisson-example-1.png){#fig-006-trace-histogram-density-plots-gamma-poisson-example width=672}\n:::\n:::\n\n\n::::\n:::::\n\n::: {.callout-note #nte-006-plots-slightly-different}\n###### My plots differ slightly from the figures in the book\n\nThe overlaid function (`ggplot2::stat_function(dgamma, args = list(shape = 13, rate = 3))`) for the Gamma-Poisson model is in the book missing.\n\nAlthough I am using the exact same code, seed, scaling, and bandwidth, I am getting a slightly different curve overlay.\n\n::: {#big-text style=\"font-size: 125%\"}\n**Most likely causes:** \n:::\n\n1. **Different R/package versions** — The textbook was written with specific versions of `rstan`, `bayesplot`, and other packages. Updates to these packages (especially `bayesplot`'s density estimation or plotting functions) could produce slightly different results even with identical code and seeds.\n\n2. **Different Stan version** — `rstan` itself may have been updated since the book was published (July 2025 cutoff). Even with the same seed, different Stan versions can produce slightly different MCMC samples due to algorithmic refinements or numerical precision changes.\n\n3. **System/compiler differences** — Stan uses C++ compilation, which can vary across different operating systems, compilers, or hardware. This could lead to minor numerical differences in the chain values themselves.\n\n4. **Random number generator differences** — R's RNG implementation or how `rstan` interfaces with it may have changed between versions.\n\n\n::: {#big-text style=\"font-size: 125%\"}\n**Summary**\n:::\n\nI think that this small differences are not a problem: If the overall shape and fit of the curves are visually similar the small differences are likely **not a problem with code or understanding**. Minor discrepancies due to software versions are normal and expected in reproducible research.\n\n:::\n\n## Markov chain diagnostics\n\nSimulation is fantastic. Even when we’re able to derive a Bayesian posterior, we can use posterior simulation to verify our work and provide some intuition. More importantly, when we’re *not* able to derive a posterior, simulated samples provide a crucial *approximation.* In the <a class='glossary' title='Markov chain Monte Carlo (MCMC) methods comprise a class of algorithms for sampling from a probability distribution. By constructing a [markov chain] that has the desired distribution as its equilibrium distribution, one can obtain a sample of the desired distribution by recording states from the chain. The more steps that are included, the more closely the distribution of the sample matches the actual desired distribution. Various algorithms exist for constructing chains. (Wikipedia)'>MCMC</a> examples above, we saw that the <a class='glossary' title='Markov chain is a stochastic model describing a sequence of possible events in which the probability of each event depends only on the state attained in the previous event.  This defining property is known as the Markov property or memorylessness, meaning the future state depends solely on the current state and not on the sequence of events that preceded it. (Brave-AI)'>Markov chains</a> traverse the sample space of our parameter ($\\pi$ or $\\lambda$) and, in the end, *mimic* a random sample that eventually *converges* to the posterior. “Approximation” and “converges” are key words here – **simulations aren’t perfect**. This begs the following questions:  \n\n- What does a good Markov chain look like? \n- How can we tell if our Markov chain sample produces a reasonable approximation of the posterior? \n- How big should our Markov chain sample size be?\n\nAnswering these questions is both an art and science. There are no one-size-fits-all magic formulas that provide definitive answers here. Rather, it’s through experience that you get a feel for what “good” Markov chains look like and what you can do to fix a “bad” Markov chain. \n\nIn this section, we’ll focus on a couple visual diagnostic tools that will get us started: \n\n- <a class='glossary' title='A trace plot is a chain visualization that plots the samples in sequential order, joined by a line. A trace plot isn’t the last th'>trace plot</a>: see also Annex @sec-906-trace-plots.\n- <a class='glossary' title='Parallel chains are a diagnostic tool used in Markov Chain Monte Carlo (MCMC) to assess convergence to the target posterior distribution.  The core idea is to run multiple independent MCMC chains from different starting points and compare their behavior. If the chains have converged to the same stationary distribution, their sample distributions should be similar, indicating reliable inference.'>parallel chain</a>: see also Annex @sec-906-parallel-chains.\n- <a class='glossary' title='Effective Sample Size (ESS) is a diagnostic tool in MCMC (Markov Chain Monte Carlo) analysis that estimates the number of independent samples equivalent to a given number of autocorrelated MCMC draws.  Because MCMC samples are typically correlated, the ESS is usually smaller than the total number of draws (N), reflecting reduced statistical efficiency.'>effective sample size</a> see also @sec-906-effective-sample-size.\n- <a class='glossary' title='Autocorrelation in MCMC is a diagnostic tool that measures the correlation between samples in a Markov chain at different lags (i.e., how similar a sample is to one that occurs a certain number of steps earlier).  It is used to assess mixing efficiency and convergence of the chain.'>autocorrelation</a>: see also @sec-906-autocorrelation.\n- <a class='glossary' title='R hat, also known as the potential scale reduction factor or Gelman-Rubin diagnostic, is a widely used convergence diagnostic for Markov Chain Monte Carlo (MCMC) methods.  It assesses whether multiple parallel chains have converged to the same target distribution by comparing the within-chain variance and the between-chain variance .'>R hat</a> ($hat{R}$): see also @sec-906-r-hat.\n\nUtilizing these diagnostics should be done holistically. Since no single visual or numerical diagnostic is one-size-fits-all, they provide a fuller picture of Markov chain quality when considered together. Further, other excellent diagnostics exist. We focus here on those that are common and easy to implement in the software packages we’ll be using.\n\n### Examining trace plots {#sec-006-examining-trace-plots}\n\nSee also Annex @sec-906-trace-plots.\n\nReexamine the trace plots for the Beta-Binomial simulation in @fig-006-trace-plot-beta-binomial-example. These are textbook examples of what we want trace plots to look like. Mainly, they look like a bunch of white noise with no discernible trends or notable phenomena. This nothingness implies that the chains are stable. In contrast, the hypothetical Markov chains for the same Beta-Binomial model shown in Figure @fig-006-bad-trace-plots illustrate potential chain behavior that should give us pause.\n\n![Trace plots (left) and corresponding density plots (right) of two hypothetical Markov chains. These provide examples of what “bad” Markov chains might look like. The superimposed black lines (right) represent the target Beta(11,3) posterior pdf.](img/906-bad-trace-plots.png){#fig-006-bad-trace-plots\nfig-alt=\"4 graphs in two rows and columns. Top left: Chain A: trace plot; x = iteration, y = pi. It shows a narrow zig-zag curve moving from the top left edge to the middle of the window. Important here is also that the amplitudes of the zig-zag are rather small, just 0.1 pi. Top right: Chain A: density plot; x = pi, y = no scale. It shows the result of the bad trace plot from chain A. Instead of a left-skewed distribution, representing the superimposed target Beta(3, 11) posterior with a maximum at 0.85 pi, the simulation shows a symmetric distribution with mode under 0.8. Bottom left: Chain B: trace plot; x = iteration, y = pi. It shows a narrow zig-zag curve, this time with big amplitudes. But in two places the zag-zag pattern is broken with a horizontal line. One horizontal line with 0.62 pi at iteration 800-1200, the other one with 0.55 pi between iteration 3000-3800. Bottom right: Chain B: Density plot; x = pi, y = no scale. Instead of a smooth left-skewed distribution, representing the superimposed target Beta(3, 11) posterior, it shows a left skewed distribution with two spikes. A bigger one at 0.55 pi, the other, smaller one at 0.62 pi.\" fig-align=\"center\" }\n\n::: {#big-text style=\"font-size: 110%\"}\n**@fig-006-bad-trace-plots: Trace plots left** \n:::\n\nThe downward trend in **Chain A** indicates that it has not yet stabilized after 5,000 iterations – it has not yet “found” or does not yet know how to explore the range of posterior plausible π values. The downward trend also hints at strong correlation among the chain values – they don’t look like independent noise. All of this to say that Chain A is mixing slowly. This is bad. Though Markov chains are inherently dependent, the more they behave like fast mixing (noisy) independent samples, the smaller the error in the resulting posterior approximation (roughly speaking). \n\n**Chain B** exhibits a different problem. As evidenced by the two completely flat lines in the trace plot, it tends to get stuck when it visits smaller values of $\\pi$.\n\n::: {#big-text style=\"font-size: 110%\"}\n**@fig-006-bad-trace-plots: Density plots right** \n:::\n\nThe density plots confirm that both of these goofy-looking chains result in a serious issue: they produce poor approximations of the $\\text{Beta}(11,3)$ posterior (superimposed in black), and thus misleading posterior conclusions. \n\n**Consider Chain A**. Since it’s mixing so slowly, it has only explored $\\pi$ values in the rough range from 0.6 to 0.9 in its first 5,000 iterations. As a result, its posterior approximation overestimates the plausibility of $\\pi$ values in this range while completely underestimating the plausibility of values outside this range. \n\n**Consider Chain B**. In getting stuck, Chain B over-samples some values in the left tail of the posterior $\\pi$ values. This phenomenon produces the erroneous spikes in the posterior approximation.\n\nIn *practice*, we run {**rstan**} simulations when we can’t specify, and thus want to approximate the posterior. This means that we won’t have the privilege of being able to compare our simulation results to the “real” posterior. This is why diagnostics are so important. If we see bad trace plots like those in @fig-006-bad-trace-plots, there are some immediate steps we can take:  \n\n1. **Check the model**. Are the assumed prior and data models appropriate? \n2. **Run the chain for more iterations**. Some undesirable short-term chain trends might iron out in the long term.  \n\nWe’ll get practice with the more nuanced Step 1 throughout the book. Step 2 is easy, though it requires extra computation time.\n\n### Comparing parallel chains {#sec-006-comparing-parallel-chains}\n\nSee also @sec-906-parallel-chains.\n\nRecall that our `rstan::stan()` simulation for the Beta-Binomial model produced four parallel Markov chains. Not only do we want to see stability in each individual chain (as discussed above), we want to see consistency across the four chains. Mainly, though we expect different chains take different paths, they should exhibit similar features and produce similar posterior approximations. \n\nFor example, the trace plots for the four parallel chains in @fig-006-trace-plot-beta-binomial-example appear similar in their randomness. Further, in the Figure 6.13 density plots, we observe that these four chains produce nearly indistinguishable posterior approximations. This provides evidence that our simulation is stable and sufficiently long – running the chains for more iterations likely wouldn’t produce drastically different or improved posterior approximations.\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-006-density-plots-individual-chains}\n: Density plots of individual chains\n::::::\n:::\n::::{.my-r-code-container}\n\n::: {.cell}\n\n```{.r .cell-code}\nbayesplot::mcmc_dens_overlay(bb_sim, pars = \"pi\") + \n  ggplot2::labs(y = \"density\")\n```\n\n::: {.cell-output-display}\n![Density plot of the four parallel Markov chains for π](006-approximating-posterior_files/figure-html/fig-006-density-plots-individual-chains-1.png){#fig-006-density-plots-individual-chains width=384}\n:::\n:::\n\n\n::::\n:::::\n\nFor a point of comparison, let’s implement a *shorter* Markov chain simulation for the same model. Instead of running four parallel chains for 10,000 iterations and a resulting sample size of 5,000 each, run four parallel chains for only 100 iterations and a resulting sample size of 50 each.\n\nThe trace plots and corresponding density plots of the short Markov chains are shown below. Though the chains’ trace plots exhibit similar random behavior, their corresponding density plots differ, hence they produce discrepant posterior approximations. In the face of such instability and confusion about which of these four approximations is the most accurate, it would be a mistake to stop our simulation after only 100 iterations.\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-006-short-markov-chain}\n: A shorter Markov chain simulation for the same model\n::::::\n:::\n::::{.my-r-code-container}\n\n::: {.cell}\n\n```{.r .cell-code}\n# STEP 2: SIMULATE the posterior\nbb_sim_short <- rstan::stan(model_code = bb_model, data = list(Y = 9), \n                     chains = 4, iter = 50*2, seed = 84735)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> SAMPLING FOR MODEL 'anon_model' NOW (CHAIN 1).\n#> Chain 1: \n#> Chain 1: Gradient evaluation took 1e-06 seconds\n#> Chain 1: 1000 transitions using 10 leapfrog steps per transition would take 0.01 seconds.\n#> Chain 1: Adjust your expectations accordingly!\n#> Chain 1: \n#> Chain 1: \n#> Chain 1: WARNING: There aren't enough warmup iterations to fit the\n#> Chain 1:          three stages of adaptation as currently configured.\n#> Chain 1:          Reducing each adaptation stage to 15%/75%/10% of\n#> Chain 1:          the given number of warmup iterations:\n#> Chain 1:            init_buffer = 7\n#> Chain 1:            adapt_window = 38\n#> Chain 1:            term_buffer = 5\n#> Chain 1: \n#> Chain 1: Iteration:  1 / 100 [  1%]  (Warmup)\n#> Chain 1: Iteration: 10 / 100 [ 10%]  (Warmup)\n#> Chain 1: Iteration: 20 / 100 [ 20%]  (Warmup)\n#> Chain 1: Iteration: 30 / 100 [ 30%]  (Warmup)\n#> Chain 1: Iteration: 40 / 100 [ 40%]  (Warmup)\n#> Chain 1: Iteration: 50 / 100 [ 50%]  (Warmup)\n#> Chain 1: Iteration: 51 / 100 [ 51%]  (Sampling)\n#> Chain 1: Iteration: 60 / 100 [ 60%]  (Sampling)\n#> Chain 1: Iteration: 70 / 100 [ 70%]  (Sampling)\n#> Chain 1: Iteration: 80 / 100 [ 80%]  (Sampling)\n#> Chain 1: Iteration: 90 / 100 [ 90%]  (Sampling)\n#> Chain 1: Iteration: 100 / 100 [100%]  (Sampling)\n#> Chain 1: \n#> Chain 1:  Elapsed Time: 0 seconds (Warm-up)\n#> Chain 1:                0 seconds (Sampling)\n#> Chain 1:                0 seconds (Total)\n#> Chain 1: \n#> \n#> SAMPLING FOR MODEL 'anon_model' NOW (CHAIN 2).\n#> Chain 2: \n#> Chain 2: Gradient evaluation took 0 seconds\n#> Chain 2: 1000 transitions using 10 leapfrog steps per transition would take 0 seconds.\n#> Chain 2: Adjust your expectations accordingly!\n#> Chain 2: \n#> Chain 2: \n#> Chain 2: WARNING: There aren't enough warmup iterations to fit the\n#> Chain 2:          three stages of adaptation as currently configured.\n#> Chain 2:          Reducing each adaptation stage to 15%/75%/10% of\n#> Chain 2:          the given number of warmup iterations:\n#> Chain 2:            init_buffer = 7\n#> Chain 2:            adapt_window = 38\n#> Chain 2:            term_buffer = 5\n#> Chain 2: \n#> Chain 2: Iteration:  1 / 100 [  1%]  (Warmup)\n#> Chain 2: Iteration: 10 / 100 [ 10%]  (Warmup)\n#> Chain 2: Iteration: 20 / 100 [ 20%]  (Warmup)\n#> Chain 2: Iteration: 30 / 100 [ 30%]  (Warmup)\n#> Chain 2: Iteration: 40 / 100 [ 40%]  (Warmup)\n#> Chain 2: Iteration: 50 / 100 [ 50%]  (Warmup)\n#> Chain 2: Iteration: 51 / 100 [ 51%]  (Sampling)\n#> Chain 2: Iteration: 60 / 100 [ 60%]  (Sampling)\n#> Chain 2: Iteration: 70 / 100 [ 70%]  (Sampling)\n#> Chain 2: Iteration: 80 / 100 [ 80%]  (Sampling)\n#> Chain 2: Iteration: 90 / 100 [ 90%]  (Sampling)\n#> Chain 2: Iteration: 100 / 100 [100%]  (Sampling)\n#> Chain 2: \n#> Chain 2:  Elapsed Time: 0 seconds (Warm-up)\n#> Chain 2:                0 seconds (Sampling)\n#> Chain 2:                0 seconds (Total)\n#> Chain 2: \n#> \n#> SAMPLING FOR MODEL 'anon_model' NOW (CHAIN 3).\n#> Chain 3: \n#> Chain 3: Gradient evaluation took 0 seconds\n#> Chain 3: 1000 transitions using 10 leapfrog steps per transition would take 0 seconds.\n#> Chain 3: Adjust your expectations accordingly!\n#> Chain 3: \n#> Chain 3: \n#> Chain 3: WARNING: There aren't enough warmup iterations to fit the\n#> Chain 3:          three stages of adaptation as currently configured.\n#> Chain 3:          Reducing each adaptation stage to 15%/75%/10% of\n#> Chain 3:          the given number of warmup iterations:\n#> Chain 3:            init_buffer = 7\n#> Chain 3:            adapt_window = 38\n#> Chain 3:            term_buffer = 5\n#> Chain 3: \n#> Chain 3: Iteration:  1 / 100 [  1%]  (Warmup)\n#> Chain 3: Iteration: 10 / 100 [ 10%]  (Warmup)\n#> Chain 3: Iteration: 20 / 100 [ 20%]  (Warmup)\n#> Chain 3: Iteration: 30 / 100 [ 30%]  (Warmup)\n#> Chain 3: Iteration: 40 / 100 [ 40%]  (Warmup)\n#> Chain 3: Iteration: 50 / 100 [ 50%]  (Warmup)\n#> Chain 3: Iteration: 51 / 100 [ 51%]  (Sampling)\n#> Chain 3: Iteration: 60 / 100 [ 60%]  (Sampling)\n#> Chain 3: Iteration: 70 / 100 [ 70%]  (Sampling)\n#> Chain 3: Iteration: 80 / 100 [ 80%]  (Sampling)\n#> Chain 3: Iteration: 90 / 100 [ 90%]  (Sampling)\n#> Chain 3: Iteration: 100 / 100 [100%]  (Sampling)\n#> Chain 3: \n#> Chain 3:  Elapsed Time: 0 seconds (Warm-up)\n#> Chain 3:                0 seconds (Sampling)\n#> Chain 3:                0 seconds (Total)\n#> Chain 3: \n#> \n#> SAMPLING FOR MODEL 'anon_model' NOW (CHAIN 4).\n#> Chain 4: \n#> Chain 4: Gradient evaluation took 0 seconds\n#> Chain 4: 1000 transitions using 10 leapfrog steps per transition would take 0 seconds.\n#> Chain 4: Adjust your expectations accordingly!\n#> Chain 4: \n#> Chain 4: \n#> Chain 4: WARNING: There aren't enough warmup iterations to fit the\n#> Chain 4:          three stages of adaptation as currently configured.\n#> Chain 4:          Reducing each adaptation stage to 15%/75%/10% of\n#> Chain 4:          the given number of warmup iterations:\n#> Chain 4:            init_buffer = 7\n#> Chain 4:            adapt_window = 38\n#> Chain 4:            term_buffer = 5\n#> Chain 4: \n#> Chain 4: Iteration:  1 / 100 [  1%]  (Warmup)\n#> Chain 4: Iteration: 10 / 100 [ 10%]  (Warmup)\n#> Chain 4: Iteration: 20 / 100 [ 20%]  (Warmup)\n#> Chain 4: Iteration: 30 / 100 [ 30%]  (Warmup)\n#> Chain 4: Iteration: 40 / 100 [ 40%]  (Warmup)\n#> Chain 4: Iteration: 50 / 100 [ 50%]  (Warmup)\n#> Chain 4: Iteration: 51 / 100 [ 51%]  (Sampling)\n#> Chain 4: Iteration: 60 / 100 [ 60%]  (Sampling)\n#> Chain 4: Iteration: 70 / 100 [ 70%]  (Sampling)\n#> Chain 4: Iteration: 80 / 100 [ 80%]  (Sampling)\n#> Chain 4: Iteration: 90 / 100 [ 90%]  (Sampling)\n#> Chain 4: Iteration: 100 / 100 [100%]  (Sampling)\n#> Chain 4: \n#> Chain 4:  Elapsed Time: 0 seconds (Warm-up)\n#> Chain 4:                0 seconds (Sampling)\n#> Chain 4:                0 seconds (Total)\n#> Chain 4:\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n#> Warning: Bulk Effective Samples Size (ESS) is too low, indicating posterior means and medians may be unreliable.\n#> Running the chains for more iterations may help. See\n#> https://mc-stan.org/misc/warnings.html#bulk-ess\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n#> Warning: Tail Effective Samples Size (ESS) is too low, indicating posterior variances and tail quantiles may be unreliable.\n#> Running the chains for more iterations may help. See\n#> https://mc-stan.org/misc/warnings.html#tail-ess\n```\n\n\n:::\n\n```{.r .cell-code}\n# Trace plots of short chains\np1 <- bayesplot::mcmc_trace(bb_sim_short, pars = \"pi\")\n\n# Density plots of individual short chains\np2 <- bayesplot::mcmc_dens_overlay(bb_sim_short, pars = \"pi\")\n\npatchwork:::\"-.ggplot\"(p1, p2)\n```\n\n::: {.cell-output-display}\n![Trace plots and density plots of the four short parallel Markov chains for π, each of length 50](006-approximating-posterior_files/figure-html/fig-006-short-markov-chain-1.png){#fig-006-short-markov-chain width=672}\n:::\n:::\n\n\n::::\n:::::\n\nThe output warns twice: \n\n1. During the sampling of the model. For each of the four chains it says: \n\n> WARNING: There aren't enough warmup iterations to fit the three stages of adaptation as currently configured. Reducing each adaptation stage to 15%/75%/10% of the given number of warmup iterations: init_buffer = 7, adapt_window = 38, term_buffer = 5\n\n2. For the calculation of the figure it says:\n\n> Warning: Bulk Effective Samples Size (ESS) is too low, indicating posterior means and medians may be unreliable. Running the chains for more iterations may help. See <https://mc-stan.org/misc/warnings.html#bulk-ess>.\n\n> Warning: Tail Effective Samples Size (ESS) is too low, indicating posterior variances and tail quantiles may be unreliable. Running the chains for more iterations may help. See <https://mc-stan.org/misc/warnings.html#tail-ess>.\n\n### Calculating effective sample size & autocorrelation\n\n#### Effective sample size {#sec-006-effective-sample-size}\n\nSee also @sec-906-effective-sample-size.\n\nRecall from @sec-006-examining-trace-plots that the more a dependent Markov chain behaves like an independent sample, the smaller the error in the resulting posterior approximation (loosely speaking).\n\nThough trace plots provide some visual insight into this behavior, supplementary numerical assessments can provide more nuanced information. To begin, recall that our Markov chain simulation `bb_sim` produced a combined 20,000 dependent values of $\\pi$, sampled from models other than the posterior. We then used this chain to approximate the posterior model of $\\pi$. Knowing that the error in this approximation is likely larger than if we had used 20,000 independent sample values drawn directly from the posterior begs the following question: Relatively, how many independent sample values would it take to produce an equivalently accurate posterior approximation? The **effective sample size ratio** provides an answer.\n\n:::::{.my-assessment}\n:::{.my-assessment-header}\n:::::: {#cor-006-effective-sample-size-ratio}\n: Effective sample size ratio\n::::::\n:::\n::::{.my-assessment-container}\n\nLet $N$ denote the actual sample size or length of a *dependent* Markov chain. The **effective sample size** of this chain, $N_{eff}$, quantifies the number of *independent* samples it would take to produce an equivalently accurate posterior approximation. The greater the $N_{eff}$ the better, yet it’s typically true that the accuracy of a Markov chain approximation is only as good as that of a smaller independent sample. That is, it’s typically true that $N_{eff} < N$ , thus the *effective sample size ratio* is less than 1:\n\n$$\\frac{N_{eff}}{N}$$\nThere’s no magic rule for interpreting this ratio, and it should be utilized alongside other diagnostics such as the trace plot. That said, we might be suspicious of a Markov chain for which the effective sample size ratio is less than 0.1, i.e., the effective sample size $N_{eff}$ is less than 10% of the actual sample size $N$t.\n\n\n::::\n:::::\n\nA quick call to the `bayesplot::neff_ratio()` function provides the estimated effective sample size ratio for our Markov chain sample of pi values. Here, the accuracy in using our 20,000 length Markov chain to approximate the posterior of $\\pi$ is roughly as great as if we had used only 34% as many *independent* values. Put another way, our 20,000 Markov chain values are about as useful as only 6800 independent samples (0.34 ⋅ 20000). Since this ratio is above 0.1, we’re not going to stress.\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-006-calculate-effective-sample-size-ratio}\n: Calculate the effective sample size ratio\n::::::\n:::\n::::{.my-r-code-container}\n\n::: {#tbl-006-calculate-effective-sample-size-ratio .cell tbl-cap='Calculation of the effective sample size ratio'}\n\n```{.r .cell-code}\n# Calculate the effective sample size ratio\nbayesplot::neff_ratio(bb_sim, pars = c(\"pi\")) |> \n  knitr::kable()\n```\n\n::: {.cell-output-display}\n\n\n|         x|\n|---------:|\n| 0.3462257|\n\n\n:::\n:::\n\n\n::::\n:::::\n\n#### Autocorrelation {#sec-006-autocorrelation}\n\nSee also @sec-906-autocorrelation.\n\nAutocorrelation provides another metric by which to evaluate whether our Markov chain sufficiently mimics the behavior of an independent sample. *Strong* autocorrelation or dependence is a bad thing – it goes hand in hand with small effective sample size ratios, and thus provides a warning sign that our resulting posterior approximations might be unreliable. \n\nWe saw some evidence of this in Chain A of @fig-006-bad-trace-plots. Now, by the simple construction of a Markov chain, there’s inherently going to be some autocorrelation among the chain values – one chain value ($\\pi^{(i)}$) depends upon the previous chain value ($\\pi^{(i-1)}$), which depends upon the one before that ($\\pi^{(i-2)}$), which depends upon the one before that ($\\pi^{(i-3})$), and so on. This chain of dependencies also means that each chain value depends in *some* degree on all previous chain values. For example, since $\\pi^{(i)}$ is dependent on $\\pi^{(i-1)}$ which is dependent on $\\pi^{(i-2)}$, $\\pi^{(i)}$ is also dependent on $\\pi^{(i-2)}$. Yet this dependence, or autocorrelation, fades. It’s like Tobler’s first law of geography: *everything is related to everything else, but near things are more related than distant things*. Thus, it’s typically the case that a chain value $\\pi^{(i)}$ is more strongly related to the previous value ($\\pi^{(i-1)}$) than to a chain value 100 steps back ($\\pi^{(i-100)}$).\n\n:::::{.my-experiment}\n:::{.my-experiment-header}\n:::::: {#def-006-autocorrelation}\n: Autocorrelation\n::::::\n:::\n::::{.my-experiment-container}\n\n**Lag 1** autocorrelation measures the correlation between pairs of Markov chain values that are one “step” apart (e.g., $\\pi^{(i)}$ and $\\pi^{(i−1)}$). \n\n**Lag 2** autocorrelation measures the correlation between pairs of Markov chain values that are two “steps” apart (e.g., $\\pi^{(i)}$ and $\\pi^{(i−2)}$). \n\nAnd so on.\n::::\n:::::\n\nLet’s apply these concepts to our `bb_sim` analysis. Check out the trace plot and **autocorrelation plot** of our simulation results in Figure 6.15. (For simplicity, we show the results for only one of our four parallel chains.)\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-006-autocorrelation}\n: Trace plot and autocorrelation plot\n::::::\n:::\n::::{.my-r-code-container}\n\n::: {.cell}\n\n```{#lst-006-autocorrelation .r .cell-code  lst-cap=\"Trace plot and autocorrelation plot for all four Markov chains\"}\np1 <- bayesplot::mcmc_trace(bb_sim, pars = \"pi\") \np2 <- bayesplot::mcmc_acf(bb_sim, pars = \"pi\")\n\npatchwork:::\"-.ggplot\"(p1, p2)\n```\n\n::: {.cell-output-display}\n![A trace plot (left) and autocorrelation plot (right) for all four Markov chains from the `bb_sim` analysis.](006-approximating-posterior_files/figure-html/fig-006-autocorrelation-1.png){#fig-006-autocorrelation width=672}\n:::\n:::\n\n\n::::\n:::::\n\n::: {.callout-caution #cau-006-autocorrelation-book-code}\n###### Book’s code does not match figure\n\nThe @lst-006-autocorrelation code does not conform to the book’s \"Figure 6.15\". With the code it shows all four chains as demonstrated in @fig-006-autocorrelation.\n\nWhat follows in the text is the correct code for \"Figure 6.15\".\n\n:::\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-006-autocorrelation-2}\n: Trace plot and autocorrelation plot of only one chain\n::::::\n:::\n::::{.my-r-code-container}\n\n\n::: {.cell}\n\n```{#lst-006-autocorrelation-2 .r .cell-code  lst-cap=\"Trace plot and autocorrelation plot for only one Markov chain\"}\n# Extract posterior draws as a matrix/array for subsetting\nposterior_array <- as.array(bb_sim)\n\n# Show trace plot for chain 1 only\np1 <- bayesplot::mcmc_trace(posterior_array[, 1, , drop = FALSE], pars = \"pi\")\n\n# Show ACF plot for chain 1 only\np2 <- bayesplot::mcmc_acf(posterior_array[, 1, , drop = FALSE], pars = \"pi\")\n\npatchwork:::\"-.ggplot\"(p1, p2)\n```\n\n::: {.cell-output-display}\n![A trace plot (left) and autocorrelation plot (right) for a single Markov chain from the `bb_sim` analysis.](006-approximating-posterior_files/figure-html/fig-006-autocorrelation-2-1.png){#fig-006-autocorrelation-2 width=672}\n:::\n:::\n\n\n***\n\nThe key is `posterior_array[, 1, , drop = FALSE]` where the second index (`1`) selects chain 1. Change it to 2, 3, or 4 for other chains.\n::::\n:::::\n\n\n\nAgain, notice that there are no obvious patterns in the trace plot. This provides one visual clue that, though the chain values are inherently dependent, this dependence is relatively weak and limited to small lags or values that are just a few steps apart. This observation is supported by the autocorrelation plot which marks the autocorrelation (y-axis) at lags 0 through 20 (x-axis). The lag 0 autocorrelation is naturally 1 – it measures the correlation between a Markov chain value and *itself.* From there, the lag 1 autocorrelation is roughly 0.5, indicating moderate correlation among chain values that are only 1 step apart. But then the autocorrelation quickly drops off and is effectively 0 by lag 5. That is, there’s very little correlation between Markov chain values that are more than a few steps apart. This is all good news. It’s more confirmation that our Markov chain is **mixing quickly**, i.e., quickly moving around the range of posterior plausible $\\pi$ values, and thus at least mimicking an independent sample.  \n\nPresuming you’ve never seen an autocorrelation plot before, we imagine that it’s not very obvious that the plot in @fig-006-autocorrelation-2 is a “good” one. For contrast, consider the results for an unhealthy Markov chain (Figure 6.16). The trace plot exhibits strong trends, and hence autocorrelation, in the Markov chain values. This observation is echoed and further formalized by the autocorrelation plot. The slow decrease in the autocorrelation curve indicates that the dependence between chain values does *not* quickly fade away. In fact, there’s a roughly 0.9 correlation between Markov chain values that are a full *20 steps apart*!\n\nSince its chain values are so strongly tied to the previous values, this chain is slow mixing it would take a long time for it to adequately explore the full range of the posterior. Thus, just as with the slow mixing Chain A in @fig-006-bad-trace-plots, we should be wary about using this chain to approximate the posterior. Let’s tie these ideas together.\n\n![A trace plot (left) and autocorrelation plot (right) for a slow mixing Markov chain of π.](img/006-autocorrelation-bad.png){#fig-006-autocorrelation-bad\nfig-alt=\"Two figures side-by-side. Left trace plot show a kind of fever chart or stock index with big waves pf pi (y-axis) during the iterations (x-axis) and additionally small changes inside the big waves. In the right plot you see a line starting from y-axis 1.0 (Autocorrelation) to end after 20 lags about 0.9 Autocorrelation.\" fig-align=\"center\" \nwidth=\"100%\"}\n\n:::::{.my-experiment}\n:::{.my-experiment-header}\n:::::: {#def-006-fast-vs-slow-mixing}\n: Fast vs slow mixing Markov chains\n::::::\n:::\n::::{.my-experiment-container}\n\n- **Fast mixing chains** exhibit behavior similar to that of an independent sample: the chains move “quickly” around the range of posterior plausible values, the autocorrelation among the chain values drops off quickly, and the effective sample size ratio is reasonably large. \n- **Slow mixing chains** do *not* enjoy the features of an independent sample: the chains move “slowly” around the range of posterior plausible values, the autocorrelation among the chain values drops off very slowly, and the effective sample size ratio is small.\n\n::::\n:::::\n\nSo what do we do if ours is a dreaded slow mixing chain? \n\n1. The first and, in our opinion best, possible solution is the tried and true “**run a longer chain**.” Even a slow mixing chain can eventually produce a good posterior approximation if we run it for enough iterations. \n2. Another common approach is to **thin the Markov chain**. For example, from our original chain of 5000 $\\pi$ values, we might keep every second value and toss out the rest: $\\{\\pi^{(2)}, \\pi^{(4)}, \\pi^{(6)}, . . . , \\pi^{(5000)}\\}$.  Or, we might keep every ten chain values: ${\\pi^{(10)}, \\pi^{(20)}, \\pi^{(30)}, . . . , \\pi^{(5000)}\\}$. By discarding the  draws in between, we remove the strong correlations at low lags. For example, $\\pi^{(20)}$ is less correlated with the previous value in the thinned chain ($\\pi^{(10)}$) than with the previous value in the original chain ($\\pi^{(19)}$).\n\n**For illustration only**, we thin out our original `bb_sim` chains to just every tenth value using the `thin` argument in `rstan::stan()`. As a result, the autocorrelation drops off a bit earlier, after 1 lag instead of 5 (@fig-006-thinned-mcmc-example). BUT, since this was *already* a quick mixing simulation with quickly decreasing autocorrelation and a relatively high effective sample size ratio, this minor improvement in autocorrelation **isn’t worth the information we lost**. Instead of a sample size of 5000 chain values, we now only have 500 values with which to approximate the posterior.\n\n:::::{.my-r-code}\n:::{.my-r-code-header}\n:::::: {#cnj-006-thinned-mcmc-example}\n: Simulate a thinned MCMC example\n::::::\n:::\n::::{.my-r-code-container}\n\n::: {.cell}\n\n```{.r .cell-code}\n# Simulate a thinned MCMC sample\nthinned_sim <- rstan::stan(model_code = bb_model, data = list(Y = 9), \n                    chains = 4, iter = 5000*2, seed = 84735, thin = 10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> SAMPLING FOR MODEL 'anon_model' NOW (CHAIN 1).\n#> Chain 1: \n#> Chain 1: Gradient evaluation took 1e-06 seconds\n#> Chain 1: 1000 transitions using 10 leapfrog steps per transition would take 0.01 seconds.\n#> Chain 1: Adjust your expectations accordingly!\n#> Chain 1: \n#> Chain 1: \n#> Chain 1: Iteration:    1 / 10000 [  0%]  (Warmup)\n#> Chain 1: Iteration: 1000 / 10000 [ 10%]  (Warmup)\n#> Chain 1: Iteration: 2000 / 10000 [ 20%]  (Warmup)\n#> Chain 1: Iteration: 3000 / 10000 [ 30%]  (Warmup)\n#> Chain 1: Iteration: 4000 / 10000 [ 40%]  (Warmup)\n#> Chain 1: Iteration: 5000 / 10000 [ 50%]  (Warmup)\n#> Chain 1: Iteration: 5001 / 10000 [ 50%]  (Sampling)\n#> Chain 1: Iteration: 6000 / 10000 [ 60%]  (Sampling)\n#> Chain 1: Iteration: 7000 / 10000 [ 70%]  (Sampling)\n#> Chain 1: Iteration: 8000 / 10000 [ 80%]  (Sampling)\n#> Chain 1: Iteration: 9000 / 10000 [ 90%]  (Sampling)\n#> Chain 1: Iteration: 10000 / 10000 [100%]  (Sampling)\n#> Chain 1: \n#> Chain 1:  Elapsed Time: 0.008 seconds (Warm-up)\n#> Chain 1:                0.009 seconds (Sampling)\n#> Chain 1:                0.017 seconds (Total)\n#> Chain 1: \n#> \n#> SAMPLING FOR MODEL 'anon_model' NOW (CHAIN 2).\n#> Chain 2: \n#> Chain 2: Gradient evaluation took 0 seconds\n#> Chain 2: 1000 transitions using 10 leapfrog steps per transition would take 0 seconds.\n#> Chain 2: Adjust your expectations accordingly!\n#> Chain 2: \n#> Chain 2: \n#> Chain 2: Iteration:    1 / 10000 [  0%]  (Warmup)\n#> Chain 2: Iteration: 1000 / 10000 [ 10%]  (Warmup)\n#> Chain 2: Iteration: 2000 / 10000 [ 20%]  (Warmup)\n#> Chain 2: Iteration: 3000 / 10000 [ 30%]  (Warmup)\n#> Chain 2: Iteration: 4000 / 10000 [ 40%]  (Warmup)\n#> Chain 2: Iteration: 5000 / 10000 [ 50%]  (Warmup)\n#> Chain 2: Iteration: 5001 / 10000 [ 50%]  (Sampling)\n#> Chain 2: Iteration: 6000 / 10000 [ 60%]  (Sampling)\n#> Chain 2: Iteration: 7000 / 10000 [ 70%]  (Sampling)\n#> Chain 2: Iteration: 8000 / 10000 [ 80%]  (Sampling)\n#> Chain 2: Iteration: 9000 / 10000 [ 90%]  (Sampling)\n#> Chain 2: Iteration: 10000 / 10000 [100%]  (Sampling)\n#> Chain 2: \n#> Chain 2:  Elapsed Time: 0.008 seconds (Warm-up)\n#> Chain 2:                0.009 seconds (Sampling)\n#> Chain 2:                0.017 seconds (Total)\n#> Chain 2: \n#> \n#> SAMPLING FOR MODEL 'anon_model' NOW (CHAIN 3).\n#> Chain 3: \n#> Chain 3: Gradient evaluation took 0 seconds\n#> Chain 3: 1000 transitions using 10 leapfrog steps per transition would take 0 seconds.\n#> Chain 3: Adjust your expectations accordingly!\n#> Chain 3: \n#> Chain 3: \n#> Chain 3: Iteration:    1 / 10000 [  0%]  (Warmup)\n#> Chain 3: Iteration: 1000 / 10000 [ 10%]  (Warmup)\n#> Chain 3: Iteration: 2000 / 10000 [ 20%]  (Warmup)\n#> Chain 3: Iteration: 3000 / 10000 [ 30%]  (Warmup)\n#> Chain 3: Iteration: 4000 / 10000 [ 40%]  (Warmup)\n#> Chain 3: Iteration: 5000 / 10000 [ 50%]  (Warmup)\n#> Chain 3: Iteration: 5001 / 10000 [ 50%]  (Sampling)\n#> Chain 3: Iteration: 6000 / 10000 [ 60%]  (Sampling)\n#> Chain 3: Iteration: 7000 / 10000 [ 70%]  (Sampling)\n#> Chain 3: Iteration: 8000 / 10000 [ 80%]  (Sampling)\n#> Chain 3: Iteration: 9000 / 10000 [ 90%]  (Sampling)\n#> Chain 3: Iteration: 10000 / 10000 [100%]  (Sampling)\n#> Chain 3: \n#> Chain 3:  Elapsed Time: 0.008 seconds (Warm-up)\n#> Chain 3:                0.007 seconds (Sampling)\n#> Chain 3:                0.015 seconds (Total)\n#> Chain 3: \n#> \n#> SAMPLING FOR MODEL 'anon_model' NOW (CHAIN 4).\n#> Chain 4: \n#> Chain 4: Gradient evaluation took 0 seconds\n#> Chain 4: 1000 transitions using 10 leapfrog steps per transition would take 0 seconds.\n#> Chain 4: Adjust your expectations accordingly!\n#> Chain 4: \n#> Chain 4: \n#> Chain 4: Iteration:    1 / 10000 [  0%]  (Warmup)\n#> Chain 4: Iteration: 1000 / 10000 [ 10%]  (Warmup)\n#> Chain 4: Iteration: 2000 / 10000 [ 20%]  (Warmup)\n#> Chain 4: Iteration: 3000 / 10000 [ 30%]  (Warmup)\n#> Chain 4: Iteration: 4000 / 10000 [ 40%]  (Warmup)\n#> Chain 4: Iteration: 5000 / 10000 [ 50%]  (Warmup)\n#> Chain 4: Iteration: 5001 / 10000 [ 50%]  (Sampling)\n#> Chain 4: Iteration: 6000 / 10000 [ 60%]  (Sampling)\n#> Chain 4: Iteration: 7000 / 10000 [ 70%]  (Sampling)\n#> Chain 4: Iteration: 8000 / 10000 [ 80%]  (Sampling)\n#> Chain 4: Iteration: 9000 / 10000 [ 90%]  (Sampling)\n#> Chain 4: Iteration: 10000 / 10000 [100%]  (Sampling)\n#> Chain 4: \n#> Chain 4:  Elapsed Time: 0.008 seconds (Warm-up)\n#> Chain 4:                0.009 seconds (Sampling)\n#> Chain 4:                0.017 seconds (Total)\n#> Chain 4:\n```\n\n\n:::\n\n```{.r .cell-code}\n# Extract posterior draws as a matrix/array for subsetting\nposterior_thinned_array <- as.array(thinned_sim)\n\n# Check out the results\np1 <- bayesplot::mcmc_trace(posterior_thinned_array[, 1, , drop = FALSE], pars = \"pi\")\np2 <- bayesplot::mcmc_acf(posterior_thinned_array[, 1, , drop = FALSE], pars = \"pi\")\n\npatchwork:::\"-.ggplot\"(p1, p2)\n```\n\n::: {.cell-output-display}\n![A trace plot (left) and autocorrelation plot (right) for a single Markov chain from the `bb_sim` analysis, thinned to every tenth value.](006-approximating-posterior_files/figure-html/fig-006-thinned-mcmc-example-1.png){#fig-006-thinned-mcmc-example width=672}\n:::\n:::\n\n\n::::\n:::::\n\nWe similarly thin our slow mixing chain down to every tenth value (@fig-006-autocorrelation-thinned). The resulting chain still exhibits slow mixing trends in the trace plot, but the autocorrelation drops more quickly than the pre-thinned chain. This is good, but is it worth losing 90% of our original sample values? We’re not so sure.\n\n![A trace plot (left) and autocorrelation plot (right) for a slow mixing Markov chain of π, thinned to every tenth value.](img/006-autocorrelation-thinned.png){#fig-006-autocorrelation-thinned\nfig-alt=\"Two figures side-by-side. Left trace plot show a kind of fever chart or stock index with big waves pf pi (y-axis) during the iterations (x-axis) and additionally small changes inside the big waves. In the right plot you see a line starting from y-axis 1.0 (Autocorrelation) to end after 20 lags about 0.25 Autocorrelation.\" fig-align=\"center\" \nwidth=\"100%\"}\n\n::: {.callout-caution #cau-thinned-chain-not-always-good}\n###### How to decide wheter or not to thin a Markov chain\n\nThere is a careful line to walk when deciding whether or not to thin a Markov chain. The benefits of reduced autocorrelation don’t necessarily outweigh the loss of precious chain values. That is, 5000 Markov chain values with stronger autocorrelation might produce a better posterior approximation than 500 chain values with weaker autocorrelation. \n\nThe effectiveness of thinning also depends in part on the algorithm used to construct the Markov chain. For example, the {**rstan**} and {**rstanarm**} packages used throughout this book employ an efficient <a class='glossary' title='Hamiltonian Monte Carlo (HMC) is a Markov chain Monte Carlo (MCMC) method used to sample from complex, high-dimensional probability distributions, particularly in Bayesian inference.  It improves upon traditional methods like Metropolis-Hastings by using gradient information from the target distribution to guide sampling, resulting in more efficient exploration of the parameter space. (Brave-AI)'>Hamiltonian Monte Carlo</a> algorithm. As such, in the current `rstan::stan()` help file, the **package authors advise against thinning** unless your simulation hogs up too much memory on your machine.\n:::\n\n\n### Calculating R-hat {#sec-006-calculating-r-hat}\n\nSee also @sec-906-r-hat.\n\nJust as effective sample size and autocorrelation provide numerical supplements to the visual trace plot diagnostic in assessing the degree to which a Markov chain behaves like an independent sample, the split-$\\hat{R}$ metric (or “R-hat” for short) provides a numerical supplement to the visual comparison of parallel chains. Recall from @sec-006-comparing-parallel-chains that, not only do we want each *individual* Markov chain in our simulation to be stable, we want there to be consistency *across* the parallel chains. R-hat addresses this consistency by comparing the variability in sampled $\\pi$ values across all chains *combined* to the variability *within* each individual chain. Before presenting a more formal definition, check your intuition.\n\n:::::{.my-assessment}\n:::{.my-assessment-header}\n:::::: {#cor-006-marker-good-mc}\n: What is a marker of a “good” Markov chain simulation?\n::::::\n:::\n::::{.my-assessment-container}\nFigure 6.19 provides simulation results for `bb_sim` (top row) along with a bad hypothetical alternative (bottom row). Based on the patterns in these plots, what do you think is a marker of a “good” Markov chain simulation?  \n\n- a. The variability in $\\pi$ values *within* any individual chain is **less than** the variability in $\\pi$ values across all chains *combined.* \n- b. The variability in $\\pi$ values *within* any individual chain is **comparable to** the variability in $\\pi$ values across all chains *combined.*\n\n![Simulation results for `bb_sim` (top row) and a hypothetical alternative (bottom row). Included are trace plots of the four parallel chains (left), density plots for each individual chain (middle), and a density plot of the combined chains (right).](img/006-r-hat-quiz.png){#fig-006-r-hat-quiz\nfig-alt=\"Top left: All four chains overly each other in a zig-zag curve with high amplitude. Top middle: The four posterior densities are very similar. Top right: The summary of all four densities is similar to their four individual densities. Bottom left: The four chains are not overlapping, Their (smaller) zig-zag curve do not overlap. Bottom middle: The four densities plot have their maximum on very different values of pi (0.70, 0.76, 0.78 and 0.84). Bottom right: The resulting combined density curve has three spikes at different pi values and the middle curve has a small bump on their top. There is no similarity between the combined and individual densities.\" fig-align=\"center\" \nwidth=\"100%\"}\n\nWhat is the correct answer <select class='webex-select'><option value='blank'></option><option value=''>a</option><option value='answer'>b</option></select>\n\n::::\n:::::\n\nTo answer this quiz, let’s dig into @fig-006-r-hat-quiz. Based on what we learned in Section @sec-006-comparing-parallel-chains, we can see that `bb_sim` is superior to the alternative – its parallel chains exhibit similar features and produce similar posterior approximations. In particular, the variability in $\\pi$ values is nearly identical *within* each chain (top middle plot). As a consequence, the variability in $\\pi$ values across all chains *combined* (top right plot) is similar to that of the individual chains. \n\nIn contrast, notice that the four parallel chains in the alternative simulation produce conflicting posterior approximations (bottom middle plot), and hence an unstable and poor posterior approximation when we combine these chains (bottom right plot). As a consequence, the range and variability in $\\pi$ values across all chains *combined* are much larger than the range and variability in $\\pi$ values *within* any individual chain.  \n\nBringing this analysis together, we’ve intuited the importance of the relationship between the variability in values across all chains *combined* and *within* the individual parallel chains. Specifically:  \n\n- in a “good” Markov chain simulation, the variability across all parallel chains combined will be roughly comparable to the variability within any individual chain;\n- in a “bad” Markov chain simulation, the variability across all parallel chains combined might exceed the typical variability within each chain.  \n\nWe can *quantify* the relationship between the combined chain variability and within-chain variability using R-hat. We provide an intuitive definition of R-hat here. For a more detailed definition, see [@vehtari2021]. And to learn more about the exciting connection between effective sample size and R-hat, see [@vats2021]!\n\n:::::{.my-theorem}\n:::{.my-theorem-header}\n:::::: {#thm-006-r-hat}\n: R-hat\n::::::\n:::\n::::{.my-theorem-container}\n\nConsider a Markov chain simulation of parameter $\\theta$ which utilizes four parallel chains. Let $Var_{combined}$ denote the variability in $\\theta$ across all four chains combined and $Var_{within}$ denote the typical variability within any individual chain. The R-hat metric calculates the ratio between these two sources of variability:\n\n$$\n\\begin{align*}\nR-hat \\approx \\sqrt\\frac{\\text{Var}_{combined}}{\\text{Var}_{within}}\n\\end{align*}\n$$\nIdeally, $R-hat \\approx 1$, reflecting stability across the parallel chains. In contrast, $R-hat > 1$ indicates instability, with the variability in the combined chains exceeding that within the chains. Though no golden rule exists, an R-hat ratio greater than $1.05$ raises some red flags about the stability of the simulation.\n\n::::\n:::::\n\nTo calculate the R-hat ratio for our simulation, we can apply the `bayesplot::rhat()` function:\n\n`bayesplot::rhat(bb_sim, pars = \"pi\")` = 1.000245.\n\nReflecting our observation that the variability across and within our four parallel chains is comparable, `bb_sim` has an R-hat value that’s effectively equal to 1. In contrast, the bad hypothetical simulation exhibited in @fig-006-r-hat-quiz has an R-hat value of 5.35. That is, the variance across all chain values combined is more than 5 *times* the typical variance within each chain. This *well* exceeds the 1.05 red flag marker, providing ample evidence that the hypothetical parallel chains do not produce consistent posterior approximations, thus the simulation is unstable.\n\n## Summary\n\nAs our Bayesian models get more sophisticated, their posteriors will become too difficult, if not impossible, to specify. In this chapter, you learned two **simulation techniques for approximating the posterior** in such scenarios: grid approximation and Markov chain Monte Carlo. Both techniques produce a **sample** of $N \\theta$ values,\n\n$$\n\\{\\theta^{(1)}, \\theta^{(2)}, . . . , \\theta^{(N)}\\}\n$$\n\nHowever, the properties of these samples differ:  \n\n- **Grid approximation** takes an **independent** sample of $\\theta^{(i)}$ from a *discretized approximation* of posterior pdf $f (\\theta \\mid y)$. This approach is nicely straightforward but breaks down in more complicated model settings. \n- **Markov chain Monte Carlo** offers a more flexible alternative. Though MCMC produces a **dependent** sample of $\\theta^{(i)}$ which are **not** drawn from the posterior pdf $f (\\theta \\mid y)$, this sample will mimic the posterior model so long as the chain length $N$ is big enough.\n\nFinally, you learned some MCMC **diagnostics** for checking the resulting simulation quality. In short, we can visually examine **trace plots** and **density plots** of multiple parallel chains for **stability** and **mixing** in our simulation:\n\nAnd we can supplement these visual diagnostics with numerical diagnostics such as **effective sample size ratio**, **autocorrelation**, and **R-hat**:\n\n```R\n# Visual diagnostics (plots)\nbayesplot::mcmc_trace(my_sim, pars = \"___\")\nbayesplot::mcmc_dens_overlay(my_sim, pars = \"___\")\n\n\n# Numerical diagnostics \nbayesplot::neff_ratio(my_sim, pars = \"___\")\nbayesplot::mcmc_acf(my_sim, pars = \"___\")\nbayesplot::rhat(my_sim, pars = \"___\")\n\n```\n\n## Exercises\n\n::: {#wrn-006-exercises .callout-warning}\n###### Take my solutions with caution!\n\nKeep in mind, that I am not an expert but a learner. This means that the\npresented solutions may have errors or are completely wrong.\n\nFor some of the exercises I have used <a class='glossary' title='Large Language Models (LLMs) are advanced artificial intelligence systems trained on massive amounts of text data to understand, generate, and manipulate human language. LLMs function as statistical prediction machines, learning patterns in language by predicting the next word in a sequence. This allows them to perform diverse tasks such as answering questions, writing essays, translating languages, summarizing documents, generating code, and even engaging in conversation. (Brave-AI)'>LLMs</a>, mostly the free <a class='glossary' title='Claude Haiku is Anthropic’s smallest, fastest, and most cost-effective model in the Claude family, designed for high-speed, low-latency tasks while maintaining strong performance on coding, computer use, and agent workflows.'>Claude Haiku</a>.\n\nIf you find errors please report to me at the [GitHub\nrepo](https://github.com/petzi53/bayes-rules) of this website.\n:::\n\n### Conceptual exercises\n\n\n\n\n## Glossary Entries {.unnumbered}\n\n\n::: {.cell}\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table\" style=\"margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> term </th>\n   <th style=\"text-align:left;\"> definition </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> Autocorrelation </td>\n   <td style=\"text-align:left;\"> Autocorrelation in MCMC is a diagnostic tool that measures the correlation between samples in a Markov chain at different lags (i.e., how similar a sample is to one that occurs a certain number of steps earlier).  It is used to assess mixing efficiency and convergence of the chain. </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Beta-Binomial-Model </td>\n   <td style=\"text-align:left;\"> The Beta-Binomial Bayesian Model is a fundamental framework in Bayesian statistics used to estimate a proportion π (e.g., success probability) when data are binary outcomes (success/failure) across n independent trials. The Beta-Binomial Bayesian Model combines a Beta prior with a Binomial likelihood, resulting in a Beta posterior due to conjugacy.  This makes it ideal for estimating unknown proportions (e.g., success rates) from binary data. </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Claude Haiku </td>\n   <td style=\"text-align:left;\"> Claude Haiku is Anthropic’s smallest, fastest, and most cost-effective model in the Claude family, designed for high-speed, low-latency tasks while maintaining strong performance on coding, computer use, and agent workflows. </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Effective Sample Size </td>\n   <td style=\"text-align:left;\"> Effective Sample Size (ESS) is a diagnostic tool in MCMC (Markov Chain Monte Carlo) analysis that estimates the number of independent samples equivalent to a given number of autocorrelated MCMC draws.  Because MCMC samples are typically correlated, the ESS is usually smaller than the total number of draws (N), reflecting reduced statistical efficiency. </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> HMC </td>\n   <td style=\"text-align:left;\"> Hamiltonian Monte Carlo (HMC) is a Markov chain Monte Carlo (MCMC) method used to sample from complex, high-dimensional probability distributions, particularly in Bayesian inference.  It improves upon traditional methods like Metropolis-Hastings by using gradient information from the target distribution to guide sampling, resulting in more efficient exploration of the parameter space. (Brave-AI) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Likelihood-Function </td>\n   <td style=\"text-align:left;\"> The likelihood function measures the plausibility of different parameter values given the observed data, rather than the probability of the data itself. It is not a probability distribution over the parameters, as it does not integrate or sum to one, and it is not normalized. Instead, it quantifies how likely the observed data are under different parameter settings. (Brave-AI) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> LLMs </td>\n   <td style=\"text-align:left;\"> Large Language Models (LLMs) are advanced artificial intelligence systems trained on massive amounts of text data to understand, generate, and manipulate human language. LLMs function as statistical prediction machines, learning patterns in language by predicting the next word in a sequence. This allows them to perform diverse tasks such as answering questions, writing essays, translating languages, summarizing documents, generating code, and even engaging in conversation. (Brave-AI) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Markov Chain </td>\n   <td style=\"text-align:left;\"> Markov chain is a stochastic model describing a sequence of possible events in which the probability of each event depends only on the state attained in the previous event.  This defining property is known as the Markov property or memorylessness, meaning the future state depends solely on the current state and not on the sequence of events that preceded it. (Brave-AI) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> MCMC </td>\n   <td style=\"text-align:left;\"> Markov chain Monte Carlo (MCMC) methods comprise a class of algorithms for sampling from a probability distribution. By constructing a [markov chain] that has the desired distribution as its equilibrium distribution, one can obtain a sample of the desired distribution by recording states from the chain. The more steps that are included, the more closely the distribution of the sample matches the actual desired distribution. Various algorithms exist for constructing chains. (&lt;a href=\"https://en.wikipedia.org/wiki/Markov_chain_Monte_Carlo\"&gt;Wikipedia&lt;/a&gt;) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Normalizing Constant </td>\n   <td style=\"text-align:left;\"> In Bayesian statistics, the normalizing constant ensures that the posterior distribution integrates to 1, making it a valid probability distribution. It is also known as the marginal likelihood or evidence, and appears in the denominator of Bayes' theorem. The integral for the normalizing constant is often intractable for complex models because it involves high-dimensional parameter spaces and there exists no closed-form solution for most realistic models. As a result, approximation methods like Markov Chain Monte Carlo (MCMC), bridge sampling, or variational inference are used to estimate or bypass the normalizing constant. (Brave-AI) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Parallel Chain </td>\n   <td style=\"text-align:left;\"> Parallel chains are a diagnostic tool used in Markov Chain Monte Carlo (MCMC) to assess convergence to the target posterior distribution.  The core idea is to run multiple independent MCMC chains from different starting points and compare their behavior. If the chains have converged to the same stationary distribution, their sample distributions should be similar, indicating reliable inference. </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> PDF </td>\n   <td style=\"text-align:left;\"> A probability density function (PDF) describes a probability distribution for a random, continuous variable. Use a probability density function to find the chances that the value of a random variable will occur within a range of values that you specify. More specifically, a PDF is a function where its integral for an interval provides the probability of a value occurring in that interval. (&lt;a href=\"https://statisticsbyjim.com/probability/probability-density-function/\"&gt;Statistics By Jim&lt;/a&gt;) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Posteriorx </td>\n   <td style=\"text-align:left;\"> The posterior distribution represents the updated beliefs about the parameters of a model after incorporating observed data. It is derived by combining the prior distribution, which reflects initial beliefs about the parameter, with the likelihood of the observed data using Bayes' theorem. </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Priorx </td>\n   <td style=\"text-align:left;\"> A prior represents the initial belief or knowledge about an uncertain quantity, such as a model parameter, before observing any data. It is formally defined as a probability distribution that quantifies the degree of belief in the parameter's possible values based on previous information, expert opinion, or theoretical considerations. </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> R hat </td>\n   <td style=\"text-align:left;\"> R hat, also known as the potential scale reduction factor or Gelman-Rubin diagnostic, is a widely used convergence diagnostic for Markov Chain Monte Carlo (MCMC) methods.  It assesses whether multiple parallel chains have converged to the same target distribution by comparing the within-chain variance and the between-chain variance . </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Trace Plot </td>\n   <td style=\"text-align:left;\"> A trace plot is a chain visualization that plots the samples in sequential order, joined by a line. A trace plot isn’t the last th </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n## Session Info {.unnumbered}\n\n::: my-r-code\n::: my-r-code-header\nSession Info\n:::\n\n::: my-r-code-container\n\n::: {.cell}\n\n```{.r .cell-code}\nsessioninfo::session_info()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> ─ Session info ───────────────────────────────────────────────────────────────\n#>  setting  value\n#>  version  R version 4.5.2 (2025-10-31)\n#>  os       macOS Tahoe 26.3.1\n#>  system   aarch64, darwin20\n#>  ui       X11\n#>  language (EN)\n#>  collate  en_US.UTF-8\n#>  ctype    en_US.UTF-8\n#>  tz       Europe/Vienna\n#>  date     2026-03-10\n#>  pandoc   3.9 @ /opt/homebrew/bin/ (via rmarkdown)\n#>  quarto   1.8.27 @ /usr/local/bin/quarto\n#> \n#> ─ Packages ───────────────────────────────────────────────────────────────────\n#>  ! package        * version  date (UTC) lib source\n#>  P abind            1.4-8    2024-09-12 [?] RSPM\n#>  P backports        1.5.0    2024-05-23 [?] RSPM\n#>    base64enc        0.1-6    2026-02-02 [1] CRAN (R 4.5.2)\n#>  P bayesplot        1.15.0   2025-12-12 [?] RSPM\n#>    bayesrules       0.0.3    2026-01-20 [1] RSPM\n#>  P boot             1.3-32   2025-08-29 [?] CRAN (R 4.5.2)\n#>  P callr            3.7.6    2024-03-25 [?] RSPM\n#>    checkmate        2.3.4    2026-02-03 [1] RSPM\n#>  P class            7.3-23   2025-01-01 [?] CRAN (R 4.5.2)\n#>  P cli              3.6.5    2025-04-23 [?] CRAN (R 4.5.0)\n#>  P codetools        0.2-20   2024-03-31 [?] CRAN (R 4.5.2)\n#>  P colourpicker     1.3.0    2023-08-21 [?] RSPM\n#>  P commonmark       2.0.0    2025-07-07 [?] RSPM\n#>  P crosstalk        1.2.2    2025-08-26 [?] RSPM\n#>  P curl             7.0.0    2025-08-19 [?] RSPM\n#>  P digest           0.6.39   2025-11-19 [?] CRAN (R 4.5.2)\n#>    distributional   0.6.0    2026-01-14 [1] RSPM\n#>  P dplyr            1.2.0    2026-02-03 [?] RSPM\n#>  P DT               0.34.0   2025-09-02 [?] RSPM\n#>  P dygraphs         1.1.1.6  2018-07-11 [?] RSPM\n#>    e1071            1.7-17   2025-12-18 [1] RSPM\n#>  P evaluate         1.0.5    2025-08-27 [?] CRAN (R 4.5.1)\n#>  P farver           2.1.2    2024-05-13 [?] RSPM\n#>  P fastmap          1.2.0    2024-05-15 [?] CRAN (R 4.5.0)\n#>  P generics         0.1.4    2025-05-09 [?] RSPM\n#>  P ggplot2          4.0.2    2026-02-03 [?] RSPM\n#>  P glossary       * 1.0.0    2023-05-30 [?] RSPM\n#>  P glue             1.8.0    2024-09-30 [?] CRAN (R 4.5.0)\n#>  P gridExtra        2.3      2017-09-09 [?] RSPM\n#>  P groupdata2       2.0.5    2024-12-18 [?] RSPM\n#>  P gtable           0.3.6    2024-10-25 [?] RSPM\n#>  P gtools           3.9.5    2023-11-20 [?] RSPM\n#>  P htmltools        0.5.9    2025-12-04 [?] CRAN (R 4.5.2)\n#>  P htmlwidgets      1.6.4    2023-12-06 [?] RSPM\n#>  P httpuv           1.6.16   2025-04-16 [?] RSPM\n#>  P igraph           2.2.1    2025-10-27 [?] RSPM\n#>  P inline           0.3.21   2025-01-09 [?] RSPM\n#>  P janitor          2.2.1    2024-12-22 [?] RSPM\n#>  P jsonlite         2.0.0    2025-03-27 [?] CRAN (R 4.5.0)\n#>  P kableExtra       1.4.0    2024-01-24 [?] RSPM\n#>  P knitr            1.51     2025-12-20 [?] CRAN (R 4.5.2)\n#>  P labeling         0.4.3    2023-08-29 [?] RSPM\n#>    later            1.4.5    2026-01-08 [1] RSPM\n#>    lattice          0.22-9   2026-02-09 [1] CRAN (R 4.5.2)\n#>  P lifecycle        1.0.5    2026-01-08 [?] RSPM\n#>  P litedown         0.9      2025-12-18 [?] RSPM\n#>    lme4             1.1-38   2025-12-02 [1] RSPM\n#>  P loo              2.9.0    2025-12-23 [?] RSPM\n#>    lubridate        1.9.5    2026-02-04 [1] RSPM\n#>    magrittr         2.0.4    2025-09-12 [1] RSPM\n#>  P markdown         2.0      2025-03-23 [?] RSPM\n#>  P MASS             7.3-65   2025-02-28 [?] CRAN (R 4.5.2)\n#>  P Matrix           1.7-4    2025-08-28 [?] CRAN (R 4.5.2)\n#>  P matrixStats      1.5.0    2025-01-07 [?] RSPM\n#>  P mime             0.13     2025-03-17 [?] CRAN (R 4.5.0)\n#>  P miniUI           0.1.2    2025-04-17 [?] RSPM\n#>  P minqa            1.2.8    2024-08-17 [?] RSPM\n#>  P nlme             3.1-168  2025-03-31 [?] CRAN (R 4.5.2)\n#>  P nloptr           2.2.1    2025-03-17 [?] RSPM\n#>  P otel             0.2.0    2025-08-29 [?] RSPM\n#>  P patchwork      * 1.3.2    2025-08-25 [?] RSPM\n#>  P pillar           1.11.1   2025-09-17 [?] RSPM\n#>  P pkgbuild         1.4.8    2025-05-26 [?] RSPM\n#>  P pkgconfig        2.0.3    2019-09-22 [?] RSPM\n#>    plyr             1.8.9    2023-10-02 [1] RSPM\n#>  P posterior        1.6.1    2025-02-27 [?] RSPM\n#>  P processx         3.8.6    2025-02-21 [?] RSPM\n#>  P promises         1.5.0    2025-11-01 [?] RSPM\n#>    proxy            0.4-29   2025-12-29 [1] CRAN (R 4.5.2)\n#>  P ps               1.9.1    2025-04-12 [?] RSPM\n#>    purrr            1.2.1    2026-01-09 [1] CRAN (R 4.5.2)\n#>    QuickJSR         1.9.0    2026-01-25 [1] RSPM\n#>  P R6               2.6.1    2025-02-15 [?] CRAN (R 4.5.0)\n#>    rbibutils        2.4.1    2026-01-21 [1] CRAN (R 4.5.2)\n#>  P RColorBrewer     1.1-3    2022-04-03 [?] RSPM\n#>    Rcpp             1.1.1    2026-01-10 [1] RSPM\n#>  P RcppParallel     5.1.11-1 2025-08-27 [?] RSPM\n#>    Rdpack           2.6.6    2026-02-08 [1] CRAN (R 4.5.2)\n#>    reformulas       0.4.4    2026-02-02 [1] RSPM\n#>    renv             1.1.7    2026-01-27 [1] RSPM\n#>  P reshape2         1.4.5    2025-11-12 [?] RSPM\n#>  P rlang            1.1.7    2025-12-20 [?] Github (tidyverse/rlang@7a519a2)\n#>  P rmarkdown        2.30     2025-09-28 [?] CRAN (R 4.5.0)\n#>  P rstan            2.32.7   2025-03-10 [?] RSPM\n#>  P rstanarm         2.32.2   2025-09-30 [?] RSPM\n#>    rstantools       2.6.0    2026-01-10 [1] RSPM\n#>    rstudioapi       0.18.0   2026-01-16 [1] RSPM\n#>    S7               0.2.1    2025-11-14 [1] CRAN (R 4.5.2)\n#>  P scales           1.4.0    2025-04-24 [?] RSPM\n#>  P sessioninfo      1.2.3    2025-02-05 [?] RSPM\n#>  P shiny            1.12.1   2025-12-09 [?] RSPM\n#>    shinyjs          2.1.1    2026-01-15 [1] RSPM\n#>  P shinystan        2.7.0    2025-12-12 [?] RSPM\n#>  P shinythemes      1.2.0    2021-01-25 [?] RSPM\n#>  P snakecase        0.11.1   2023-08-27 [?] RSPM\n#>  P StanHeaders      2.32.10  2024-07-15 [?] RSPM\n#>  P stringi          1.8.7    2025-03-27 [?] RSPM\n#>  P stringr          1.6.0    2025-11-04 [?] RSPM\n#>    survival         3.8-6    2026-01-16 [1] CRAN (R 4.5.2)\n#>  P svglite          2.2.2    2025-10-21 [?] RSPM\n#>  P systemfonts      1.3.1    2025-10-01 [?] RSPM\n#>  P tensorA          0.36.2.1 2023-12-13 [?] RSPM\n#>  P textshaping      1.0.4    2025-10-10 [?] RSPM\n#>  P threejs          0.3.4    2025-04-21 [?] RSPM\n#>    tibble           3.3.1    2026-01-11 [1] RSPM\n#>    tidyr            1.3.2    2025-12-19 [1] RSPM\n#>  P tidyselect       1.2.1    2024-03-11 [?] RSPM\n#>    timechange       0.4.0    2026-01-29 [1] RSPM\n#>  P V8               8.0.1    2025-10-10 [?] RSPM\n#>    vctrs            0.7.1    2026-01-23 [1] RSPM\n#>    viridisLite      0.4.3    2026-02-04 [1] RSPM\n#>  P webexercises   * 1.1.0    2023-05-15 [?] RSPM\n#>  P withr            3.0.2    2024-10-28 [?] RSPM\n#>    xfun             0.56     2026-01-18 [1] RSPM\n#>    xml2             1.5.2    2026-01-17 [1] RSPM\n#>  P xtable           1.8-4    2019-04-21 [?] RSPM\n#>    xts              0.14.1   2024-10-15 [1] RSPM\n#>  P yaml             2.3.12   2025-12-10 [?] CRAN (R 4.5.2)\n#>    zoo              1.8-15   2025-12-15 [1] RSPM\n#> \n#>  [1] /Users/petzi/Documents/Meine-Repos/bayes-rules/renv/library/macos/R-4.5/aarch64-apple-darwin20\n#>  [2] /Users/petzi/Library/Caches/org.R-project.R/R/renv/sandbox/macos/R-4.5/aarch64-apple-darwin20/4cd76b74\n#> \n#>  * ── Packages attached to the search path.\n#>  P ── Loaded and on-disk path mismatch.\n#> \n#> ──────────────────────────────────────────────────────────────────────────────\n```\n\n\n:::\n:::\n\n:::\n:::\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}